Update backend package for deal with snapshots
startupjs/startupjs pull request #1121
Opened 2023-12-04 07:11 UTC by okwergot

2023-12-06 13:09 UTC, pvturchik requested changes

2023-12-06 13:09 UTC, pvturchik commented on packages/backend/mingo-sqlite.js
> +  sqlite = await createSqlDb(path.join(process.cwd(), DB_PATH || 'sqlite.db'))
может не заниматься переопределениями переменных а написать явно

```js
const sourceSqliteDbPath = DB_LOAD_SNAPSHOT ? ... : undefined // 
const targetSqliteDbPath = DB_PATH || 'sqlite.db'
const targetSqliteDb = ...

if (sourceSqliteDbPath) {
  const sourceSqliteDb = ...
  // загружаем все в target
}

загружаем target в mingo

патчим target + mingo
```

2023-12-06 13:09 UTC, pvturchik commented on packages/backend/mingo-sqlite.js
> +  sqlite = await createSqlDb(path.join(process.cwd(), DB_PATH || 'sqlite.db'))
можно там snapshotSqliteDb, sqliteDb можно типо назвать

2023-12-06 13:33 UTC, okwergot commented on packages/backend/mingo.js
> +  const sqlDb = await createSqlDb(snapshotPath)
почему get? 
вызов функции всегда создает новый инстанс и потом возращает его в качестве результата

2023-12-06 13:38 UTC, okwergot commented on packages/backend/mingo-persist.js
> +const sourcePath = DB_LOAD_SNAPSHOT || DB_PATH || 'sqlite.db'
он есть строчкой ниже
let sqliteDb = await createSqlDb(path.join(process.cwd(), sourcePath))

2023-12-07 13:32 UTC, pvturchik commented on packages/backend/mingo-sqlite.js
> +import { cloneSqlDb, createSqlDb, loadDataToMingo } from './helpers.js'
cloneSqliteDb, createSqlDb -> getSqliteDb ?

2023-12-07 13:40 UTC, pvturchik commented on packages/backend/mingo-sqlite.js
> +function patchMingoCommit (sqliteDb, shareDbMingo) {
patchMingoForSQLitePersistence?

2023-12-07 15:15 UTC, pvturchik approved these changes

2023-12-07 15:15 UTC, merged