Sharedb-access package
startupjs/startupjs pull request #276
Opened 2020-09-17 09:42 UTC by ssstelsss

2020-09-24 21:05 UTC, cray0000 requested changes

2020-09-24 21:05 UTC, cray0000 commented on packages/backend/index.js
> +const registrationOrmRules = require('@startupjs/sharedb-access').registrationOrmRules
`registerOrmRules`, так как это название функции, то первое слово должно быть глаголом

2020-09-24 21:05 UTC, cray0000 commented on packages/sharedb-access/README.md
> +static accessControl = {
надо упростить апи, оно должно быть следующим:

1. функции deny это глупость, они слишком сложны для понимания.

2. просто надо поумолчанию запрещать все и потом уже просто указывать allow на 'create' 'read' 'update' 'delete' ну и 'all' для всех


3. этот allow надо задавать в самих orm'ках точно так же как задается schema

4. апи для задания должно быть таким:

``` js
class UserModel {
  static schema = {},
  static access = {
    all: () => {},
    read: () => {},
    update:
    create:
 
    delete:
 
  }
}
```

ну и соответственно из поля access берутся просто все поля и запускаются соответствующие функции для данной коллекции: allowRead, allowUpdate и т.д.

2020-09-25 12:01 UTC, ssstelsss commented on packages/backend/index.js
> +const registrationOrmRules = require('@startupjs/sharedb-access').registrationOrmRules
done

2020-09-25 12:01 UTC, ssstelsss commented on packages/sharedb-access/README.md
> +static accessControl = {
done

2020-09-25 13:15 UTC, cray0000 requested changes

2020-09-25 13:15 UTC, cray0000 commented on packages/sharedb-access/README.md
> +  Create: async (docId, doc, session) => { your code }
create read update delete с маленькой буквы. С большой буквы начинаются только названия классов.

2020-09-25 13:19 UTC, cray0000 commented on packages/sharedb-access/README.md
> +  Create: async (docId, doc, session) => { your code }
если тебе надо с большой буквы, то под капотом уже преобразовывай просто в большую букву непосредственно при формировании имени функции для вызова. 
name.charAt(0) + name.slice(1)

2020-09-25 14:14 UTC, ssstelsss commented on packages/sharedb-access/README.md
> +  Create: async (docId, doc, session) => { your code }
done

2020-09-25 16:04 UTC, cray0000 approved these changes
lgtm

2020-09-29 18:03 UTC, merged