Refactoring shadows
startupjs/startupjs pull request #315
Opened 2020-10-19 15:04 UTC by ssstelsss

![image](https://user-images.githubusercontent.com/58818714/96469022-6dd25680-1235-11eb-87ab-cb1923d2b87d.png)
![image](https://user-images.githubusercontent.com/58818714/96469066-788ceb80-1235-11eb-9fcd-486c3d96cf3d.png)

2020-10-19 20:22 UTC, pturchik commented on packages/ui/styles/shadows.styl
> +shadow(level=1)
ты проверял на `android`, `ios` случай когда к примеру есть тень у элемента и ты ему даешь `styleName` с `shadow(0)` чтобы убрать тень, сработает? в доке по rn не вижу `none` для тени, проверь плиз

2020-10-19 20:22 UTC, pturchik commented on packages/ui/styles/shadows.styl
> -    shadowColor: '#000',
я бы этот merge оставил чисто ради того чтобы в конфиге $UI их можно было переопредилть а в mixin использовал бы $UI.shadows.1, .... 
таким образом можно как раз в компонентах сделать Object.keys(STYLES.shadows) чтобы не писать 0, 1, 2, 3, 4, 5 ручками если что поменяется.

2020-10-21 15:49 UTC, ssstelsss commented on packages/ui/styles/shadows.styl
> +shadow(level=1)
done

2020-10-22 12:11 UTC, pturchik requested changes

2020-10-22 12:11 UTC, pturchik commented on packages/ui/styles/shadows.styl
> +    elevation: $UI.shadows[''+level].elevation
```
shadow(level=1)
  _shadow = $UI.shadows[''+level]
  if shadow
     ...
  else
    box-shadow none
    elevation 0
```

2020-10-22 12:11 UTC, pturchik commented on packages/ui/components/popups/Drawer/index.js
> +          Animated.View.shadow(
.content

2020-10-22 12:11 UTC, pturchik commented on packages/ui/components/popups/Popover/index.styl
> +  for level in _shadowLevels
`shadow(3)`

2020-10-22 12:11 UTC, pturchik commented on packages/ui/components/popups/Dropdown/index.js
> +        shadowLevel=2
-

2020-10-22 12:11 UTC, pturchik commented on packages/ui/components/popups/Dropdown/index.js
> +        shadowLevel=2
DEPERCATED: move popoverStyleWrapper to styleName

2020-10-22 14:10 UTC, ssstelsss commented on packages/ui/components/popups/Popover/index.styl
> +  for level in _shadowLevels
done

2020-10-22 14:10 UTC, ssstelsss commented on packages/ui/components/Div/index.js
>            clickable: isWeb && isClickable,
done

2020-10-22 15:01 UTC, pturchik approved these changes

2020-10-22 15:01 UTC, merged