feat(ui): Custom tag for Multiselect + docs
startupjs/startupjs pull request #317
Opened 2020-10-20 09:03 UTC by vladagurets

- Added ability to use custom element for tag in Multiselect component
- Updated docs + added ru docs

2020-10-20 10:43 UTC, pturchik commented
у тебя там в компоненте всякие `= renderOpt`, `= renderTag`. перепиши их просто на вызов компонент. тебе же там не нужно замыкать никакие пропсы свыше

2020-10-20 10:44 UTC, pturchik requested changes

2020-10-20 10:44 UTC, pturchik commented on packages/ui/components/forms/Multiselect/Multiselect.ru.mdx
> +
было бы в целом не плохо написать про опции что они могут быть примитивами / массив объектов типа label, value

2020-10-20 10:44 UTC, pturchik commented on packages/ui/components/forms/Multiselect/Multiselect.ru.mdx
> +
можно написать что нибудь в духе - You can pass custom component to `tagComponent` property that displays instead of default tag.

2020-10-20 10:44 UTC, pturchik commented on packages/ui/components/forms/Multiselect/Multiselect.ru.mdx
> +
написать о том что `onChange` тригериться на какие действия и с каким значением

2020-10-20 10:44 UTC, pturchik commented on packages/ui/components/forms/Multiselect/multiselect.web.js
>    showOptsMenu,
это обработчики насколько я понял, почему их не назвать `onShow`, `onHide` а ещё даже лучше наверное `onOpen`, `onClose` ?

2020-10-21 06:02 UTC, vladagurets commented on packages/ui/components/forms/Multiselect/multiselect.web.js
>    showOptsMenu,
Это не обработчик, это тригер, который форсит определенное дейстивие - показ выпадаюзего списка

2020-10-21 06:19 UTC, vladagurets commented
> renderOpt

Так намного удобнее читать код. Помимо рендера в логике этих методов есть и другая логика, писать ее в разметке - не очень хорошая идея
![image](https://user-images.githubusercontent.com/12694171/96680493-4b982000-137e-11eb-8f58-43c80f626583.png)

2020-10-21 06:20 UTC, vladagurets commented
> у тебя там в компоненте всякие `= renderOpt`, `= renderTag`. перепиши их просто на вызов компонент. тебе же там не нужно замыкать никакие пропсы свыше

Так намного удобнее читать код. Помимо рендера в логике этих методов есть и другая логика, писать ее в разметке - не очень хорошая идея
![image](https://user-images.githubusercontent.com/12694171/96680650-95810600-137e-11eb-9046-86b672b27b22.png)

2020-10-21 14:48 UTC, pturchik requested changes

2020-10-21 14:48 UTC, pturchik commented on packages/ui/components/forms/Multiselect/Multiselect.en.mdx
> +- `onChange` - the callback triggered when the value is changed. Returns an array with selected values | ```function(value: Array)```
ну раз уже тип пишешь то обычно он пишется сразу в начале
`onChange (function(value: Array))` или чет такое

2020-10-21 14:48 UTC, pturchik commented on packages/ui/components/forms/Multiselect/multiselect.js
> +      styleContent=styles.nativeListContent
уже бы изменил в дровере на contentStyle и кидал contentStyleName ?

2020-10-21 15:03 UTC, pturchik requested changes

2020-10-21 15:03 UTC, pturchik commented on yarn.lock
> +"@dmapper/stylus-hash-plugin@^0.0.1":
? октуда это тут

2020-10-21 15:31 UTC, ssstelsss commented on packages/ui/components/forms/Multiselect/Multiselect.ru.mdx
> +- `onChange` - коллбек, который вызывается при смене щначения поля. Возвращает массив с выбранными значениями | ```function(value: Array)```
*значения

2020-10-21 15:33 UTC, lupenq commented on packages/ui/components/forms/Multiselect/input.js
> +            record=record
Можно подумать над заменой record на просто children

2020-10-21 15:37 UTC, pturchik commented on packages/ui/components/forms/Multiselect/input.js
>    showOpts,
`onOpen`

2020-10-21 15:39 UTC, pturchik requested changes

2020-10-21 15:39 UTC, pturchik commented on packages/ui/components/forms/Multiselect/multiselect.js
> +      Div.suggestion(onPress=selectCb(selected, item.value))
`onSelect`, `onItemPres`, ...

2020-10-21 15:42 UTC, pturchik requested changes

2020-10-21 15:42 UTC, pturchik commented on packages/ui/components/forms/Multiselect/multiselect.web.js
>    `
а зачем тебе реализация веб и не веб которая на 99% одинакова?

2020-10-21 16:00 UTC, pturchik requested changes

2020-10-26 10:01 UTC, pturchik requested changes

2020-10-26 10:17 UTC, pturchik requested changes

2020-10-26 10:17 UTC, pturchik commented on packages/ui/components/forms/Multiselect/multiselect.js
> +      FlatList(
так а зачем тебе на нативе flatlist, этому есть какое-то объяснение?

2020-10-26 10:17 UTC, pturchik commented on packages/ui/components/forms/Multiselect/multiselect.js
>        showOpts=showOpts
не совсем понимаю зачем тебе состояние на верхнем уровне `showOpts` если ты его просто дальше кидаешь вместе с его сеттером дальше ? может его просто и написать там где нужно и назвать как-то более понятно раз он использует для `focused`?

2020-10-26 10:17 UTC, pturchik commented on packages/ui/components/forms/Multiselect/index.js
> +        Span.sugText= item.label
чем тебя не устроил чекбокс с label что надо тут было свое напилить ? +)

2020-10-26 11:22 UTC, vladagurets commented on packages/ui/components/forms/Multiselect/multiselect.js
>        showOpts=showOpts
а какая разница? назову я его focused, но он все равно должен быть наверху, так как состояния менюшки с сагешнами как раз таки и контролируется из родителя. И чтоб не дублировать код я поднял стейт до родителя
Из-за различия реализации веб и нейтив инпута (там попап, а там дровер) мы не можем вынести MultiselectInput в родителя

2020-10-26 11:31 UTC, vladagurets commented on packages/ui/components/forms/Multiselect/multiselect.js
> +      styleContent=styles.nativeListContent
![image](https://user-images.githubusercontent.com/12694171/97167483-8b507480-178f-11eb-8e07-e4a20883dacd.png)
![image](https://user-images.githubusercontent.com/12694171/97167513-973c3680-178f-11eb-8cd0-5d08bcd033c8.png)

в мастере все то же

2020-10-26 11:51 UTC, pturchik approved these changes

2020-10-26 11:51 UTC, pturchik commented on packages/ui/components/forms/Multiselect/index.styl
> +  margin 1u
марджин обычно используется когда отступ одного элемента нужен от другого. а тут у тебя самостоятельный элемент которому нужно иметь base вокруг себя.
```
Div(style={ padding: 1u })
  Checkbox
```

2020-10-26 11:51 UTC, merged