datepicker: safari implementation
startupjs/startupjs pull request #346
Opened 2020-11-10 06:10 UTC by frenz1e

<img width="743" alt="Screenshot 2020-11-10 at 03 19 31" src="https://user-images.githubusercontent.com/2113983/98634553-1ae05080-2356-11eb-834c-1cf16f4af14b.png">
<img width="927" alt="Screenshot 2020-11-10 at 01 56 10" src="https://user-images.githubusercontent.com/2113983/98634559-1d42aa80-2356-11eb-9195-f7df64b7ac85.png">
<img width="851" alt="Screenshot 2020-11-10 at 01 55 58" src="https://user-images.githubusercontent.com/2113983/98634562-1ddb4100-2356-11eb-869d-6740b8a2cc55.png">

2020-11-10 13:17 UTC, cray0000 requested changes

2020-11-10 13:17 UTC, cray0000 commented on packages/ui/components/forms/DateTimePicker/index.web.js
> +    if isSafari
а че не просто if else на isSafari?

2020-11-10 13:17 UTC, cray0000 commented on packages/ui/components/forms/DateTimePicker/SafariDateTimePicker/index.js
> +import 'react-datepicker/dist/react-datepicker-cssmodules.css'
вот эти стили походу никак все равно не юзаются, так как в styleName ты их нигде не указываешь, а классические css файлы у нас ток с сервака можно подтащить

2020-11-11 17:22 UTC, frenz1e commented on packages/ui/components/forms/DateTimePicker/SafariDateTimePicker/index.js
> +import 'react-datepicker/dist/react-datepicker-cssmodules.css'
я не знаю что это за магия, но оно работает, как видишь на скринах стили из пакета

2020-11-12 09:28 UTC, frenz1e commented on packages/ui/components/forms/DateTimePicker/SafariDateTimePicker/index.js
> +import 'react-datepicker/dist/react-datepicker-cssmodules.css'
~~я не знаю что это за магия, но оно работает~~ Стили просто импортятся инлайном
<img width="581" alt="Screenshot 2020-11-12 at 16 22 42" src="https://user-images.githubusercontent.com/2113983/98921566-0b066f00-2504-11eb-8cc0-63f8be02ba6e.png">

2020-11-14 12:34 UTC, simonprod commented on packages/ui/components/forms/DateTimePicker/SafariDateTimePicker/index.js
> +import 'react-datepicker/dist/react-datepicker-cssmodules.css'
мб на проде их не будет, т.к. другой модуль юзается в webpack (просто предположение, недавно такая беда была с вендорными стилями)

2020-12-02 12:58 UTC, cray0000 commented
Closing this PR in favor of the one which supersedes it: https://github.com/startupjs/startupjs/pull/402

2020-12-02 12:58 UTC, closed without merging