ref(App): add crticialVersion middleware + criticalVersion in UpdateApp component
startupjs/startupjs pull request #362
Opened 2020-11-16 09:31 UTC by lupenq

<img width="318" alt="Снимок экрана 2020-11-16 в 12 20 51" src="https://user-images.githubusercontent.com/25533519/99235912-88352b00-2807-11eb-9d26-61dabb691712.png">

2020-11-17 12:49 UTC, pturchik commented on packages/app/client/components/UpdateApp/index.js
> +        Link(to=emailLink)=supportEmail
space

2020-11-17 12:57 UTC, pturchik approved these changes

2020-11-19 11:36 UTC, pturchik commented
поправь README.md о том как теперь должно и что прокидываться.
допиши пожалуйста ещё про эти пропсы что нибудь такое, может текст получше придумаешь
- useGlobalInit={() => { // things that need to be initialized once }}
- goToHandler={(url, options, goTo) => { //  hook before going to url, be sure to call goTo at the end }}
- errorPages: { 404: <div>404 NOT FOUND</div>, ... }

2020-11-20 02:07 UTC, cray0000 requested changes

2020-11-20 02:07 UTC, cray0000 commented on docs/migration-guides/0.29.md
> +- **App**: remove deprecated `initUpdateApp` from `app/server
и надо добавить ссылку на секцию из предыдущего гайда миграции, где описано какой новый синтаксис и как на него перейти.

2020-11-20 02:07 UTC, cray0000 commented on docs/migration-guides/0.29.md
> +- **App**: remove deprecated `initUpdateApp` from `app/server
чтобы люди не искали по предыдущим гайдам че мы там когдато задепрекейтили и что им теперь делать

2020-11-20 07:57 UTC, lupenq commented on docs/migration-guides/0.29.md
> +- **App**: remove deprecated `initUpdateApp` from `app/server
Не нашёл в гайдах этот депрекейтед. Дописал сам и добавил ссылку на ридми App

2020-11-20 09:37 UTC, pturchik approved these changes

2020-11-23 13:31 UTC, ssstelsss commented on packages/app/server/initApp.js
> +export default async function initApp (backend, CRITICAL_VERSION) {
давай назовем CRITICAL_VERSION маленькими буквами с кемелкейсом, переменные названные большими буквами устоявшееся обозначение для констант

2020-11-23 13:31 UTC, ssstelsss commented on packages/app/server/initApp.js
> +  backend.CRITICAL_VERSION = CRITICAL_VERSION
это точно нужно?

2020-11-23 13:35 UTC, lupenq commented on packages/app/server/initApp.js
> +export default async function initApp (backend, CRITICAL_VERSION) {
done

2020-11-23 13:35 UTC, lupenq commented on packages/app/server/initApp.js
> +  backend.CRITICAL_VERSION = CRITICAL_VERSION
nope

2020-11-23 14:07 UTC, ssstelsss approved these changes

2020-11-23 17:39 UTC, pturchik requested changes

2020-11-23 17:39 UTC, pturchik commented on styleguide/server/index.js
> +import { CRITICAL_VERSION } from '../config.json'
import { CRITICAL_VERSION } from 'nconf'

2020-11-23 17:39 UTC, pturchik commented on styleguide/.env
> +ANDROID_UPDATE_LINK='market://details?id=company.example.app'
ну в env.production уже тоже запихни critical versions

2020-11-23 17:39 UTC, pturchik commented on packages/app/server/initApp.js
> -  })
эта мидлвара должна остаться в пакете а не чтобы её руками везде писали одну и туже. это способ доставки сессии на клиент и он вшит в наш App

2020-11-23 17:39 UTC, pturchik commented on styleguide/server/index.js
> +    expressApp.get('/api/serverSession', function (req, res) {
убирай мидлвара должна остаться в пакете

2020-11-23 17:39 UTC, pturchik commented on packages/app/README.md
> +    expressApp.get('/api/serverSession', function (req, res) {
убирай мидлвара должна остаться в пакете App

2020-11-23 17:39 UTC, pturchik commented on docs/migration-guides/0.29.md
> +- **App**: remove deprecated `initUpdateApp` from `app/server`. Change `initUpdateApp` function to `initApp` function. [See more](https://github.com/startupjs/startupjs/tree/master/packages/app)
напиши о том что починили работу version, чтобы они были реактивными и то что она теперь хранится в БД

2020-11-23 17:39 UTC, pturchik commented on packages/app/client/helpers/useNeedUpdate.js
> +  const newOsVersion = version && version.criticalVersion && version.criticalVersion[OS]
ты можешь сделать проще

```
const [version, $version] = useDoc(...)
const newOsVersion = $version.get(`criticalVersion.${OS}`)
```

2020-11-23 17:39 UTC, pturchik commented on packages/app/client/helpers/useNeedUpdate.js
> +    newOsVersion &&
на самом деле можно проверять на !== null чтобы допускать 0 версию

2020-11-24 09:06 UTC, lupenq commented on packages/app/client/helpers/useNeedUpdate.js
> +    newOsVersion &&
return (
    currentOsVersion + 1 &&
    newOsVersion + 1 &&
    currentOsVersion < newOsVersion
  )

Реализовал таким образом поддержку 0 версий для проверки

2020-11-24 13:18 UTC, pturchik requested changes

2020-11-24 13:18 UTC, pturchik commented on styleguide/server/index.js
> +  ee.on('backend', async backend => {
```
(ee, options) => {
  initApp(ee, CRITICAL_VERSION)
}
```

App.js

`ee.on('backend', ...)`

2020-11-24 13:18 UTC, pturchik commented on packages/app/client/helpers/useNeedUpdate.js
> +    newOsVersion + 1 &&
а если в проекте не задана criticalversion ? или в БД пустой документ потому что для сервера не задано ?

2020-11-24 13:18 UTC, pturchik commented on packages/app/client/helpers/useNeedUpdate.js
> +    newOsVersion + 1 &&
это какая-то мутная проверка. `undefined + 1` может выйти.  проверяй просто

`currentOsVersion !== null && newOsVersion !== null && currentOsVersion < newOsVersion`

2020-11-24 13:18 UTC, pturchik commented on packages/app/README.md
> +  })
`initApp(ee, CRITICAL_VERSION)` и в App навешиваешь листенер

2020-11-24 13:18 UTC, pturchik commented on packages/app/server/initApp.js
> +  if (!criticalVersion) return
ee.on('backend', ...)
ee.on('routes', ...)

2020-11-24 15:41 UTC, cray0000 requested changes

2020-11-24 15:41 UTC, cray0000 commented on styleguide/config.json
> +  }
почему для клиента задаются энв переменные отдельные, а для сервака почемуто внезапно обьектом?

Для сервака тоже надо тогда их назвать
`ANDROID_CRITICAL_VERSION` и т.д.

А лучше сразу зарефакторить наоборот. Если ты эмулируешь обьект через энв переменную, то и называть надо соответствующим образом. Как в обьекте ты бы стучался к значению `criticalVersion.web` - так и энв переменную надо называть - `CRITICAL_VERSION_WEB`.

То же касается и ссылки на обновление приложения - `UPDATE_LINK_ANDROID`, `UPDATE_LINK_IOS`, а не наоборот.

2020-11-25 08:47 UTC, pturchik requested changes

2020-11-25 08:47 UTC, pturchik commented on packages/app/server/initApp.js
> +      const model = backend.createModel({ fetchOnly: true })
`fetchOnly` уже можно не писать, у нас всегда на сервере автоматом создается модель с `fetchOnly`. это где-то в наших пакетах срверных мы вшили)

2020-11-25 08:47 UTC, pturchik commented on packages/app/server/initApp.js
> +        await $version.setDiffDeep('criticalVersion', { ...criticalVersion })
а смысл делать копию при `set'e`?

2020-11-25 08:47 UTC, pturchik commented on packages/app/README.md
> +      // Callback that will be processed every time before going to url. You must pass the third argument `goTo`
you must pass the third argument goto? не совсем пойму что ты имеешь ввиду. 

тут надо сказать о том что нужно вызвать goto в своем goto handler'е с конечным url

2020-11-25 08:47 UTC, pturchik commented on packages/app/README.md
> +    "web": 1
на сервере тогда тоже сделай названия всех переменных как в .env файле
CRITICAL_VERSION_IOS
CRITICAL_VERSION_ANDROID
CRITICAL_VERSION_WEB

и собирай нужный тебе объект уже там при передаче

2020-11-25 12:12 UTC, pturchik approved these changes

2020-11-25 12:49 UTC, pturchik approved these changes

2020-11-26 13:15 UTC, cray0000 approved these changes

2020-11-26 13:15 UTC, merged