Added catch access error and screen for 'Access deny'
startupjs/startupjs pull request #363
Opened 2020-11-17 08:25 UTC by ssstelsss

![image](https://user-images.githubusercontent.com/58818714/99364844-8a5ebe80-28c7-11eb-9a55-1a889b024073.png)

2020-11-20 01:55 UTC, cray0000 requested changes

2020-11-20 01:55 UTC, cray0000 commented on packages/app/client/index.js
> +        AccessDeny
прокидывай наверн accessError как message пропс в AccessDeny и показывай его там как-нить адекватно. И сделай, чтобы сообщение было внутри Card со светло-красным бэкграундом (какойнить $UI.colors.errorLightest), чтобы понятно было сразу, что это ошибка. Ну и сам текст ошибки красным $UI.colors.error

2020-11-20 01:55 UTC, cray0000 commented on packages/app/client/index.js
> +        AccessDeny
И еще показывай в AccessDeny кнопку ниже по-центру "Go back", при нажатии на которую удаляй ошибку из `_session` и программно редиректи сразу на '/' просто - `emit('url', '/')`

2020-11-20 01:55 UTC, cray0000 commented on packages/app/client/components/AccessDeny/index.js
> +      title='Sorry. Access deny!'
доступ запрещен - Access denied!

2020-11-20 13:12 UTC, ssstelsss commented on packages/app/client/index.js
> +        AccessDeny
done

2020-11-20 13:12 UTC, ssstelsss commented on packages/app/client/components/AccessDeny/index.js
> +      title='Sorry. Access deny!'
done

2020-11-23 14:06 UTC, lupenq approved these changes

2020-11-24 03:54 UTC, cray0000 approved these changes
@pturchik можно мерджить

2020-11-24 15:21 UTC, merged