Added NumberInput component
startupjs/startupjs pull request #365
Opened 2020-11-17 20:17 UTC by olvipi

2020-11-18 11:42 UTC, ssstelsss commented on packages/ui/components/forms/NumberInput/index.js
> +  function renderInput (standalone) {
возможно аргумент standalone здесь не нужен, так как в теле данной функции он не используется. Или, может быть, при копировании что-то потерялось, так как на строке 85, есть какая-то задумка под этот аргумент.

2020-11-18 11:42 UTC, ssstelsss commented on packages/ui/components/forms/NumberInput/input.js
> +      regexp = new RegExp('^-?\\d*(\\.(\\d{0,' + precision + '})?)?$')
зачем использовать два разных способа записи регулярных выражений на промежутке в 3 строки? Думаю, стоит выбрать один и использовать его в обоих случаях

2020-11-18 12:39 UTC, olvipi commented on packages/ui/components/forms/NumberInput/index.js
> +  function renderInput (standalone) {
там при layoot='pure' можно применить свои стили

2020-11-18 12:40 UTC, olvipi commented on packages/ui/components/forms/NumberInput/input.js
> +      regexp = new RegExp('^-?\\d*(\\.(\\d{0,' + precision + '})?)?$')
первый только для целых чисел и не принимает запятую

2020-11-20 02:26 UTC, cray0000 requested changes

2020-11-20 02:26 UTC, cray0000 commented on packages/ui/components/forms/NumberInput/NumberInput.ru.mdx
> +      precision={3}
precision лишний, избавься от него. Определяться должна точность просто по step параметру, который поумолчанию 1. Если step выставили 0.01 - значит у тебя 2 знака после запятой. Если 0.001 - значит 3 знака и т.д. Так же работает и input(type='number') в обычном html

2020-11-20 07:56 UTC, olvipi commented on packages/ui/components/forms/NumberInput/NumberInput.ru.mdx
> +      precision={3}
ок, просто step я планировал не для точности а именно для кастомного шага кнопок, например точность 0 а шаг 5, тоесть инпут принимает только целые числа и при смене числа кнопками оно меняется на +- 5

2020-11-20 12:32 UTC, simonprod commented on packages/ui/components/forms/NumberInput/NumberInput.ru.mdx
> +
Ниже тоже раздел "Кнопки" есть

2020-11-20 12:32 UTC, simonprod commented on packages/ui/components/forms/NumberInput/NumberInput.ru.mdx
> +
Дублируется описание

2020-11-20 12:32 UTC, simonprod commented on packages/ui/components/forms/NumberInput/index.js
> +    typeof onBlur === 'function' && onBlur(...args)
Я думаю `typeof onBlur === 'function'` должны проверять propTypes
А тут просто, onBlur && onBlur()
И на сколько я знаю, в событиях обычно 1 аргумент event передается, так что `...args` возможно тоже лишнее

2020-11-20 12:32 UTC, simonprod commented on packages/ui/components/forms/NumberInput/index.js
> +  function renderInput (standalone) {
Плюсую, `standalone` не используется в самой функции, и не понятно зачем он здесь

2020-11-20 12:32 UTC, simonprod commented on packages/ui/components/forms/NumberInput/index.js
> +  if (pure) return renderInput(true)
true - не используется

2020-11-20 12:32 UTC, simonprod commented on packages/ui/components/forms/NumberInput/input.js
> +    if (/^0\.(\d0*)?1$/.test(String(step))) return step
Желательно бы в константу релугярку засунуть, чтобы понимать интуитивно по названию для чего она нужна

2020-11-20 12:32 UTC, simonprod commented on packages/ui/components/forms/NumberInput/input.js
> +      regexp = new RegExp('^-?\\d*(\\.(\\d{0,' + stepCount + '})?)?$')
Так же желательно в константу, так никто не поймет что это за регулярка

2020-11-20 12:32 UTC, simonprod commented on packages/ui/components/forms/NumberInput/input.js
> +  ]
StyleSheet.flatten

2020-11-20 12:38 UTC, olvipi commented on packages/ui/components/forms/NumberInput/index.js
> +    typeof onBlur === 'function' && onBlur(...args)
проптайпс проверит и покажет ошибку, но если onBlur не функция будет больно

2020-11-20 12:40 UTC, olvipi commented on packages/ui/components/forms/NumberInput/NumberInput.ru.mdx
> +
спасибо

2020-11-20 12:47 UTC, olvipi commented on packages/ui/components/forms/NumberInput/index.js
> +    typeof onBlur === 'function' && onBlur(...args)
вот что будет если не проверить на typeof 
![image](https://user-images.githubusercontent.com/46069436/99801776-3fe77700-2b3f-11eb-92d5-d25b31fd740c.png)

2020-11-20 12:59 UTC, simonprod commented on packages/ui/components/forms/NumberInput/index.js
> +    typeof onBlur === 'function' && onBlur(...args)
onBlur - не может быть ничем другим кроме как функцией

2020-11-20 14:05 UTC, olvipi commented on packages/ui/components/forms/NumberInput/index.js
> +    typeof onBlur === 'function' && onBlur(...args)
onBlur это то что ты передадиш, если ты ошибочно передал нефункцию то на вебе тебе покажут ошибку проптайпсы и каждый раз при вызове будет ошибка в консоле что вызывается нефункция, а на устройстве у тебя покжется ошибка от проптайпсов, а при вызове приложение крашнется как на скрине

2020-11-20 14:37 UTC, olvipi commented on packages/ui/components/forms/NumberInput/index.js
> +  function renderInput (standalone) {
согласен

2020-11-20 14:37 UTC, olvipi commented on packages/ui/components/forms/NumberInput/NumberInput.ru.mdx
> +
спсибо

2020-11-20 14:38 UTC, olvipi commented on packages/ui/components/forms/NumberInput/index.js
> +  if (pure) return renderInput(true)
убрал wrapperStyle

2020-11-20 17:30 UTC, simonprod commented on packages/ui/components/forms/NumberInput/index.js
> +    typeof onBlur === 'function' && onBlur(...args)
Ну не зря же мы пишем propTypes, если сказано что должно быть функцией, то все других вариантов нет. Если разраб отправляет что-то другое, ну хз, наверное что-то с ним не так
Только 2 варианта, либо эта переменная есть и она функция, либо ее просто нет и она undefined

2020-11-20 18:49 UTC, olvipi commented on packages/ui/components/forms/NumberInput/index.js
> +    typeof onBlur === 'function' && onBlur(...args)
либо она object, string, etc

2020-11-23 13:03 UTC, simonprod approved these changes

2020-11-24 03:27 UTC, cray0000 approved these changes
мне не нравится, что происходит копипаст практически всего TextInput'a с добавлением функционала обработки чисел поверх этого. Но впринципе для первой версии норм, да и как правильно сделать декомпозицию TextInput'a чтобы его части и стили переиспользовать легко можно было, я до конца еще не знаю.

Так что я думаю можно мерджить, @pturchik, апи вроде нормальное (хотя наличие обоих onChange и onChangeNumber смущают, и наверн onChange надо выпилить вообще будет потом, я не понял зачем он нужен).

2020-11-24 07:25 UTC, olvipi commented
onChange я специально оставил для доступа к эвенту если понадобится

2020-11-24 12:17 UTC, cray0000 commented
ok

On Tue, Nov 24, 2020, 09:25 Oleksandr Pishchuk <notifications@github.com>
wrote:

> onChange я специально оставил для доступа к эвенту если понадобится
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/startupjs/startupjs/pull/365#issuecomment-732708801>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFDAKEEZNSYHV2NA7NLBJDSRNNX5ANCNFSM4TZBQB4Q>
> .
>

2020-11-24 12:25 UTC, olvipi commented
+ onChangeNumber возвращает число а onChange форматированый текст
'-'  1 - 0 2 - '-'
'2.' 1 - 2 2 - '2.'

2020-11-24 15:17 UTC, merged