@startupjs/mail [W]
startupjs/startupjs pull request #371
Opened 2020-11-19 19:49 UTC by tohellandback

WIP

2020-11-20 02:12 UTC, cray0000 commented on packages/mail-provider-mailgun/README.md
> +#### Tamplates
tEmplates и дальше по тексту

2020-11-20 02:12 UTC, cray0000 commented on packages/mail-provider-mailgun/README.md
> +#### Tamplates
поставь себе плагин для spellchecking'a

2020-11-27 00:41 UTC, pturchik requested changes

2020-11-27 00:41 UTC, pturchik commented on packages/mail/server/api/sendEmail.js
> +  if (!layout) return defaultLayout(options)
добавляй дефолтный лаяут в список лаяутов если его нет. зачем тебе эти мутки тут. вдруг я захочу дефолтный переопределить

2020-11-27 00:41 UTC, pturchik commented on packages/mail/server/api/sendEmail.js
> +import conf from 'nconf'
разбей пожалуйста этот файл на несколько логических сгруппированных

2020-11-27 00:41 UTC, pturchik commented on packages/mail/layouts/index.js
> +  return { html: '%{content}%', ignoreUnsubscribed: false }
темплейтам задается флаг ignore

2020-11-27 00:41 UTC, pturchik commented on packages/mail/server/api/sendEmail.js
> +    return false
сначала проверяй на whitelist/ смысл лезть в БД если он в игноре

2020-11-27 00:41 UTC, pturchik commented on packages/mail/server/api/sendEmail.js
> +  const authsCount = $auths.getExtra()
не нужно подписываться в цикле. подпишись заранее на всех.

2020-12-11 16:31 UTC, closed without merging