feat(AutoSuggest/Dropdown): key events [WIP]
startupjs/startupjs pull request #383
Opened 2020-11-25 12:55 UTC by simonprod

2020-11-25 22:37 UTC, cray0000 requested changes

2020-11-25 22:37 UTC, cray0000 commented on packages/ui/components/AutoSuggest/index.js
> +      document.keydown = null
1. почему выше .onkeydown а ниже просто .keydown.
2. у тебя мемори лики -- что будет с document.onkeydown если компонент уничтожится внезапно при переходе на другую страницу, к примеру?
3. что будет, если у тебя другой компонент на странице тоже захочет трекать клавиатуру? Он тоже тупо перезапишет свой .onkeydown и затрет твой, или наоборот ты затрешь его?

2020-11-25 22:55 UTC, simonprod commented on packages/ui/components/AutoSuggest/index.js
> +      document.keydown = null
1 - опечатка
2 - да, нужно очистить в "return ()=>"
3 - подразумевалось что может существовать только 1 открытый дропдаун на странице, соотвественно когда он открыт события на клаву работают для него, когда закрывается события очищаются и их может другой дропдаун заюзать. Можно конечно вешать события для каждого компонента отдельно, но на данный момент 2 дропдауна скорее даже не смогут нормально работать т.к. одна модалка будет поверх другой

2020-11-26 20:21 UTC, cray0000 commented on packages/ui/components/AutoSuggest/index.js
> +      document.keydown = null
3. что если у тебя вообще другой компонент на странице тоже хочет трекать клавиатуру? Например в лингве у нас на странице с игрой трекаются нажатия влево-вправо и пробел для навигации по карточкам. А вот внутри карточек как раз может юзаться дропдаун твой, к примеру в довесок. И твой дропдаун тогда выходит перетрет обработчик клавы там.

Глянь как другие это решают. Я уверен, что то, что ты тупо глобальное поле одно перезаписываешь у document - это один из самых неправильных вариантов как ловить глобально на странице нажатия кнопок.

2020-11-26 21:46 UTC, closed without merging