feat(AutoSuggest/Dropdown): key events
startupjs/startupjs pull request #394
Opened 2020-11-26 21:47 UTC by simonprod

2020-11-27 14:17 UTC, ssstelsss commented on packages/ui/components/AutoSuggest/AutoSuggest.ru.mdx
> +  if (selectIndexValue === index) {
код в примере на русском и на английском различаются, возможно изменил что-то в одном, а во втором не исправил

2020-11-27 23:11 UTC, pturchik commented
а что за файлы android, ios добавились? зачем они?

2020-11-28 16:04 UTC, simonprod commented
> а что за файлы android, ios добавились? зачем они?
Когда делаешь yarn bootstrap, после установки всех зависимостей запускается postinstall, в нем щас есть скрипт yarn fonts, собственно yarn fonts и генерит эти 2 файла

2020-11-30 14:28 UTC, cray0000 requested changes

2020-11-30 14:28 UTC, cray0000 commented on packages/ui/components/popups/Dropdown/index.js
> +      document.onkeydown = onKeyDown
`document.addEventListener` наверн тут тоже надо юзать, как ты сделал в AutoSuggest компоненте

2020-11-30 15:34 UTC, simonprod commented on packages/ui/components/popups/Dropdown/index.js
> +      document.onkeydown = onKeyDown
done

2020-11-30 15:45 UTC, cray0000 approved these changes

2020-11-30 15:46 UTC, merged