ref(Modal): use RN Modal for web
startupjs/startupjs pull request #397
Opened 2020-11-27 17:36 UTC by lupenq

2020-11-27 23:08 UTC, pturchik requested changes

2020-11-27 23:08 UTC, pturchik commented on packages/ui/components/Modal/index.js
> +  if (props.variant === 'pure') {
pure решили переименовать в custom

2020-12-01 22:13 UTC, pturchik requested changes

2020-12-01 22:13 UTC, pturchik commented on packages/ui/components/Modal/ModalHeader/index.js
> +    if children
странное условие. если не будет заголовка то и крестика не будет а он должен быть.

варианты которые возможны

заголовок
заголовок + крестик
крестик

поэтому || тебе на showCross надо вернуть над Row.

кстати ты можешь объявлять дефолтные значения в компонентах кусочках как здесь взять и объявить defaultProps = { showCross: true } а в Modal.index.js в defaultProps вставить showCross: ModalHeader.defaultProps.showCross.

2020-12-02 08:40 UTC, pturchik requested changes

2020-12-02 08:40 UTC, pturchik commented on packages/ui/components/Modal/index.js
> +  onRequestClose: PropTypes.func,
по идеи эта функция по дефолту должна закрывать модалку так же клик по крестику или по backdrop'у.

2020-12-02 08:40 UTC, pturchik commented on yarn.lock
> -"@startupjs/auth-azuread@file:packages/auth-azuread":
ты разобрался почему удалились пакеты авторизации из yarn.lock ?

2020-12-02 08:40 UTC, pturchik commented on packages/ui/components/Modal/index.js
> +  onClose: PropTypes.func,
onClose -> onCancel наверное будет более логичнее если смотреть на onConfirm, которые включают дефолтные кнопки cancel, ok.

2020-12-02 08:50 UTC, pturchik requested changes

2020-12-02 08:50 UTC, pturchik commented on packages/ui/components/Modal/layout.js
> +    $visible.set(false)
я думаю что visible.set надо делать как дефолт, если что-то прокинуто то они должны сами закрыть модалку.

2020-12-02 08:50 UTC, pturchik commented on packages/ui/components/Modal/layout.js
> +    $visible.set(false)
они сами будут закрывать модалку в своих обработчиках. ты должен дать просто функционал

onCrossPress || onCancel || visible.set(false)
onBackdropPress || onCancel || visible.set(false)
и так со всем. дефолтно ты закрываешь если ничего не прокинули и если не стоят там флаги всякие что запретить нажатие

2020-12-07 10:51 UTC, pturchik requested changes

2020-12-07 10:51 UTC, pturchik commented on packages/ui/components/Modal/layout.js
> +
давай назовем как-то осмысленно эту функцию, что-то типо `defaultClose`, `close`, `closeFallback`...

2020-12-07 10:51 UTC, pturchik commented on packages/ui/components/Modal/index.styl
> +.custom
не вижу чтобы этот класс накидывался

2020-12-07 10:51 UTC, pturchik commented on packages/ui/components/Modal/index.styl
> +.custom
по идеи он теперь вообще не нужен если кастомную мы решили просто открывать модалку с чилдреном, или что мы там решили тогда на коле?

2020-12-07 10:51 UTC, pturchik commented on packages/ui/components/Modal/index.js
> +        onRequestClose=onRequestClose
это свойство обязательное на некоторых платформах поэтому надо объявить пустую функцию по умолчанию как это было раньше с комментом

2020-12-07 10:51 UTC, pturchik commented on packages/ui/components/Modal/index.js
> +        statusBarTranslucent=statusBarTranslucent
давай писать обработчики в конце всех свойств

2020-12-07 10:51 UTC, pturchik commented on packages/ui/components/Modal/index.js
> +      statusBarTranslucent=statusBarTranslucent
я думаю ты можешь использовать один вызов модалки и внутри решать что рендерить. style будет всегда лететь в RNModal, а для layout'а можно назвать его как-то другому
```
if variant !== 'custom'
  Layout(....)
```

2020-12-07 10:51 UTC, pturchik commented on packages/ui/components/Modal/Modal.en.mdx
>  import Button from '../Button'
было бы хорошо не просто подправить доку а дописать о каких-то новых штуках, не о всех прям конечно но стоило бы. к примеру в самом вверху доки можно написать что мы наследуемся от RNModal, чтоб люди понимали что там можно поискать тоже описание пропсов, всякие onCancel, onConfirm, onBackdropPress, showCross, onCrossPress - это наши новые штуки и о них бы стоило добавить в доку описание

2020-12-07 10:51 UTC, pturchik commented on docs/migration-guides/0.30.md
> +- **Modal**: the API of the Modal component has changed. [See more](https://startupjs-ui.dmapper.co/docs/components/Modal)
было бы хорошо расписать что поменялось, людям заглянув в доку нужно будет найти соответствие того как было и как стало, им проще будет перейти если ты напишешь
- add ...
- add ..
- move ...
- rename ...

2020-12-07 10:51 UTC, pturchik commented on packages/docs/client/components/Props/Renderer/index.js
> +    props = { ...props, $visible }
тебе это не понадобится если ты в модалке сделаешь по примеру сайдбара, используя useComponentId() и будешь писать в _session.Modal[componentId] или как-то так.

тогда она сможет работать без прокидывания $visible. причем тогда нужно будет указать в доке что модалка может быть uncontrolled, это хороший кейс потому что модалки часто бывают простые что-то показать и тебе не нужно контролировать ничего, единственное что может понадобится показать onConfirm, onCancel тогда в этом случае можно будет кидать функцию close в onConfirm из модалки в них чтоб они у себя вызвали её

@cray0000 что думаешь

2020-12-07 10:51 UTC, pturchik commented on packages/ui/components/Modal/layout.js
> +    showCross,
я думаю тебе нет необходимости тут кидать showCross, onCrossPress, ты можешь здесь решить все
onCrossPress: showCross ? ... : ... а там уже показывать крестик если для него есть обработчик

2020-12-07 10:57 UTC, pturchik requested changes

2020-12-07 10:57 UTC, pturchik commented on packages/ui/components/Modal/index.js
> +  ;({ visible } = useBind({ $visible, visible }))
можно ещё кинуть 

```
let onChangeVisible
;({ visible, onChangeVisible } = useBind({ $visible, visible, onChangeVisible }))

function close () {
  onChangeVisible(false)
}
```

2020-12-07 12:26 UTC, cray0000 commented on packages/docs/client/components/Props/Renderer/index.js
> +    props = { ...props, $visible }
хорошая идея. uncontrolled вариант надо добавить. И я думаю для uncontrolled варианта, если у нас стандартные кнопки юзаются, и у них onConfirm и onCancel есть, тогда close не надо в них даже кидать.

Просто вызываем close сами после того как эти onConfirm и onCancel отработали. Ну и обе эти функции могут быть асинхронные, как у кнопки. Так что надо смотреть вернули ли они промис (то бишь проверять на наличие поля .then у результата), и дожидаться этот промис через await, и вызывать сразу после этого close тупо внутри компонента автоматом.

А для того случая, когда человек захочет кастомные кнопки написать, к примеру, либо же вызвать .close()  как-то руками самостоятельно у uncontrolled компонента -- надо сделать, чтобы был метод .close() у самого инстанса компонента.

Чтобы можно было через useRef() запихнуть модалку в переменную и от нее вызвать .close() руками когда хочется. Это делается через https://reactjs.org/docs/hooks-reference.html#useimperativehandle

2020-12-07 12:26 UTC, cray0000 commented on packages/docs/client/components/Props/Renderer/index.js
> +    props = { ...props, $visible }
@lupenq @pturchik

2020-12-07 14:41 UTC, pturchik commented on packages/docs/client/components/Props/Renderer/index.js
> +    props = { ...props, $visible }
ещё можешь добавить ref.show()

2020-12-11 14:19 UTC, cray0000 requested changes

2020-12-11 14:19 UTC, cray0000 commented on styleguide/package.json
> +    "react-native-web": "0.14.3",
этого не должно быть, react-native-web теперь в зависимостях у ui указан и он поставится и так.

2020-12-11 16:10 UTC, pturchik requested changes

2020-12-11 16:10 UTC, pturchik commented on packages/ui/components/Modal/layout.js
> +      : React.createElement(ModalHeader, headerProps)
забыл?

2020-12-14 09:04 UTC, pturchik requested changes

2020-12-14 09:04 UTC, pturchik commented on packages/ui/components/Modal/index.js
> +    if ($visible) $visible.ref($_visible)
надо ещё уничтожить рефку при дестрое,
```js
useLayoutEffect(() => {
  if (!visible) return
  $visible.ref($_visible)
  return () => $visible.removeRe()
}, [])
```

2020-12-14 09:04 UTC, pturchik commented on packages/ui/components/Modal/index.js
> +  const isUncontrolled = !$visible
тебе по идеи это не нужно

2020-12-14 22:17 UTC, pturchik requested changes

2020-12-14 22:17 UTC, pturchik commented on yarn.lock
> +  integrity sha512-On3cPbVhNgHtMK+f/V6mVE1EJUc6m9hl0sBmaWT9I3PXdrZD0n7GY5SYZFVsJw6kKW8Ge89+q8LJPXRYkI3hWw==
почему лок поменялся? может это из-за приключений с тем что были какие-то переустановки потом ты их подтирал. попробуй вернуть как было и поставить пакеты, если после этого он поменяется снова то ок отпишись мы вопрос с локом закроем

2020-12-14 22:17 UTC, pturchik commented on docs/migration-guides/0.30.md
> +  - add `showCross`, `onCrossPress`, `enableBackdropPress`, `supportedOrientations`, `$visible`, `onOrientationChange`
ты уже либо перечисли все onDismiss, onShow и прочее либо напиши showCross, onCrossPress, enableBackdropPress, $visible - это те что наши + react native modal props допиши уже как-то либо перечисляй все

2020-12-14 22:17 UTC, pturchik commented on packages/ui/components/Modal/Modal.en.mdx
> +The Modal component inherits from [React Native Modal](https://reactnative.dev/docs/modal), you can use all its props.
если ты посмотришь в доки другие то inherit секцию мы пишем всегда в одном месте.

2020-12-14 22:17 UTC, pturchik commented on packages/ui/components/Modal/Modal.en.mdx
> +- `onBackdropPress` callback, which is executed when clicking on the area around the modalk
modalk -> modal

2020-12-14 22:17 UTC, pturchik commented on packages/ui/components/Modal/Modal.en.mdx
> +- `onDismiss` callback, which is executed after closing the modalk in any way
modalk -> modal

2020-12-14 22:17 UTC, pturchik commented on packages/ui/components/Modal/Modal.en.mdx
> +You don't need to create your `useValue` and pass its setter to the modal. To control the state of the modal, you can create a variable with `const modalRef = useRef()` and pass it to the modal `ref=
modalk -> modal

2020-12-14 22:17 UTC, pturchik commented on packages/ui/components/Modal/Modal.en.mdx
> +You don't need to create your `useValue` and pass its setter to the modal. To control the state of the modal, you can create a variable with `const modalRef = useRef()` and pass it to the modal `ref=
мне кажется тебе в самом начале надо сказать что модалка бывает uncontrolled и controlled а уж потом обо всех остальных возможностях. потому что все остальные возможности никак не связаны с тем что модалка может быть uncontrolled, controlled.

вот пример uncontrolled смотрите - она сама всегда закроет модалку после любого из действий onCrossPress, onCancel, onConfirm.

а вот есть controlled - в ней onCancel, onConfirm сами не закроют модалку, и контролировать вы её можете с помощью прокидывания скоуп модели $visible или с помощью прокидывания ref'ки которая получит методы show, close. 


а то сейчас ты в uncontrolled рассказываешь почему-то про controlled через ref.

2020-12-14 22:17 UTC, pturchik commented on packages/ui/components/Modal/layout.js
> +    onConfirm && onConfirm()
наверное надо проверять если промис то ждать.
const promise = onConfirm && onConfirm()
if (promise.then) await promise
closeFallback

2020-12-14 22:17 UTC, pturchik commented on packages/ui/components/Modal/layout.js
> +    onCancel && onCancel()
аналогично

2020-12-15 10:15 UTC, pturchik commented
тебе надо проверить ещё все компоненты popups что работают ок так как они могут быть завязаны какие-то на модалку

2020-12-15 12:04 UTC, cray0000 approved these changes

2020-12-16 09:15 UTC, pturchik approved these changes

2020-12-16 09:15 UTC, merged