[BREAKING CHANGES] Created global models for sharedb-access
startupjs/startupjs pull request #400
Opened 2020-12-01 13:34 UTC by ssstelsss

2020-12-02 13:14 UTC, cray0000 requested changes

2020-12-02 13:14 UTC, cray0000 commented on packages/backend/index.js
> +    global.__clients[userId] = model
если уж у тебя это названо `__clients` (клиенты), то значит это уже какое-то общее место для сохранения чего угодно, связанного с подключающимися sharedb-шными клиентами. Тогда имеет смысл уже чтобы это было объектом, и в будущем мы туда может что-то еще будет добавлять.

```js
if (!global.__clients[userId]) = global.__clients[userId] = {}
global.__clients[userId].model = model
```

Либо если ты хочешь только модели хранить, то и назови соответствующим образом: 
```js
global.__clientModels
```

но мне лично нравится вариант с тем, чтобы сразу сделать `global.__clients` универсальным местом хранения разных данных.

2020-12-02 14:31 UTC, ssstelsss commented on packages/backend/index.js
> +    global.__clients[userId] = model
done

2020-12-07 12:14 UTC, pturchik requested changes

2020-12-07 12:14 UTC, pturchik commented on docs/migration-guides/0.30.md
> +  hasParentPermission(permission, collection, doc, session)
мы теперь получается если захотим переопределить в orm модели `static access` чтоб сделать что-то свое, то у нас ничего не выйдет, так как скорее всего в своей функции понадобится model, чтобы что-то замутить, а текущих параметров маловато будет. поэтому наверное надо в подключении этого всего сделать что-то типо здесь вместо бинда https://github.com/pturchik/startupjs/blame/master/packages/sharedb-access/lib/index.js#L36:
```js
(...params) => {
  const model = global.__clients[userId].model
  const collection = ...
  access.read(model, collection, ...params)
}
```

https://github.com/pturchik/startupjs/blame/master/packages/sharedb-access/lib/index.js#L36
https://github.com/pturchik/startupjs/blame/master/packages/sharedb-access/README.md#L43
https://bitbucket.org/dmapper/core/annotate/master/packages/permissions/access/checkCrudPermissions.js#cl-7

смотря на эти файлы я чет не совсем ещё пойму почему тако список параметров
по идеи всегда же будет collection, docId, doc, session ?

@cray0000

2020-12-07 12:52 UTC, cray0000 commented on docs/migration-guides/0.30.md
> +  hasParentPermission(permission, collection, doc, session)
да, меня тоже оба замечания беспокоили, и надо оба фиксить:

1. не должно быть такого, что где-то `collection` передается, а где-то нет. Надо чтобы он всегда передавался. Даже если он не юзается, ничего страшного, но аргументы у функций должны быть одинаковые, иначе отличие в одном аргументе запутывает.
2. надо не убирать `backend` полностью из функции, а вместо `backend` передавать `model`.

@pturchik @ssstelsss

2020-12-08 23:13 UTC, pturchik requested changes

2020-12-08 23:13 UTC, pturchik commented on packages/sharedb-access/lib/index.js
>        const globalCollectionName = collectionName.replace(/\.\*$/u, '')
globalCollectionName? почему global? может назовем 
const collection = pattern.replace(...)

2020-12-08 23:13 UTC, pturchik commented on packages/sharedb-access/lib/index.js
> +        const collection = globalCollectionName
и просто потом будешь использовать collection, а не переприсваивать для яркого названия )

2020-12-08 23:13 UTC, pturchik commented on docs/migration-guides/0.30.md
> +  hasParentPermission(permission, collection, doc, session)
доку забыл обновить?

2020-12-09 12:29 UTC, ssstelsss commented on packages/sharedb-access/lib/index.js
>        const globalCollectionName = collectionName.replace(/\.\*$/u, '')
done

2020-12-09 12:29 UTC, ssstelsss commented on packages/sharedb-access/lib/index.js
> +        const collection = globalCollectionName
done

2020-12-09 12:30 UTC, ssstelsss commented on docs/migration-guides/0.30.md
> +  hasParentPermission(permission, collection, doc, session)
done

2020-12-09 21:12 UTC, pturchik requested changes

2020-12-09 21:12 UTC, pturchik commented on docs/migration-guides/0.30.md
> +  hasParentPermission(permission, model, collection, docId, doc, session)
эти же функции объявлены не здесь а в core. тебе надо написать о том что у access параметры поменялись и все.

2020-12-09 21:12 UTC, pturchik commented on packages/sharedb-access/lib/index.js
> +      const collection = collectionName.replace(/\.\*$/u, '')
может мы все таки collectionName переименуем в pattern, ormPattern или что-то такое? потому что collection и collectionName одно и тоже по сути, а то что тебе прилетает ща в collectionName это больше pattern, match pattern, ...
так же можно поменять название этой переменной в shraedb-access чтобы было понятно.

2020-12-10 09:37 UTC, ssstelsss commented on packages/sharedb-access/lib/index.js
> +      const collection = collectionName.replace(/\.\*$/u, '')
done

2020-12-10 09:37 UTC, ssstelsss commented on docs/migration-guides/0.30.md
> +  hasParentPermission(permission, model, collection, docId, doc, session)
done

2020-12-10 10:58 UTC, merged