fix(ui->Select): fix select text and caret when focussed with Tab
startupjs/startupjs pull request #405
Opened 2020-12-02 14:13 UTC by ssstelsss

2020-12-02 17:28 UTC, cray0000 requested changes

2020-12-02 17:28 UTC, cray0000 commented on packages/ui/components/forms/TextInput/input.js
> +  const isSelect = !!renderWrapper
вот это уже жесткий костыль. Потому что renderWrapper необязатеоьно селект, это общий пропс.

Если у тебя цель это сделать так, чтобы инпут был нередактируемый, то явно сделай для этого какойнить дополнительный пропс. Если этот пропс должен быть непубличный, назови его просто с нижним подчеркиванием - типа `_editable`.

А если ты делаешь так, что почему-то TextInput должен знать про то, что снаружи его использует Select - то это уже называется 'leaky abstractions' и идет вразрез инкапсуляции.

2020-12-03 12:55 UTC, cray0000 commented
@ssstelsss ты проверил что ничего не сломал?

2020-12-04 18:38 UTC, pturchik requested changes

2020-12-04 18:38 UTC, pturchik commented on packages/ui/components/forms/TextInput/input.js
> +        editable=editable && !disabled
а разве нужно не || ?

2020-12-05 13:16 UTC, cray0000 commented on packages/ui/components/forms/TextInput/input.js
> +        editable=editable && !disabled
должно быть вроде &&, но проблема в том, что @ssstelsss не проверил походу другие компоненты, кроме селекта, а они я уверен сломались, потому что нужно дать дефолтный `true` для `editable`

2020-12-07 08:50 UTC, pturchik commented on packages/ui/components/forms/TextInput/input.js
> +        editable=editable && !disabled
а ну вот поэтому я и подумал про || потому что нет дефолта. тогда бы !disabled перекрыл)

2020-12-07 11:00 UTC, pturchik commented
используй defaultProps, propTypes

2020-12-07 22:44 UTC, pturchik requested changes

2020-12-07 22:44 UTC, pturchik commented on packages/ui/components/forms/TextInput/input.js
> +}
тебе эти пропсы надо объявить в TextInput/index.js чтоб Sandbox их показал на странице с докой

2020-12-07 22:44 UTC, pturchik commented on packages/ui/components/forms/Select/index.js
> +      selection={start: 0,end: 0}
missing space

2020-12-08 09:32 UTC, ssstelsss commented on packages/ui/components/forms/TextInput/input.js
> +}
done

2020-12-08 09:34 UTC, ssstelsss commented on packages/ui/components/forms/Select/index.js
> +      selection={start: 0,end: 0}
done

2020-12-08 11:23 UTC, cray0000 approved these changes

2020-12-08 13:18 UTC, pturchik approved these changes

2020-12-08 13:18 UTC, merged