fix(ui -> Dropdown): style
startupjs/startupjs pull request #413
Opened 2020-12-07 22:30 UTC by simonprod

2020-12-08 23:26 UTC, pturchik requested changes

2020-12-08 23:26 UTC, pturchik commented on packages/ui/components/popups/Drawer/index.js
> +        onRequestOpen()
а если его не прокинули ? может onRequestOpen && onRequestOpen() ?

2020-12-08 23:26 UTC, pturchik commented on packages/ui/components/popups/Dropdown/index.js
> +    if (activePosition >= curHeight - 10) {
а -10 это что за магия?)

2020-12-08 23:26 UTC, pturchik commented on packages/ui/components/popups/Dropdown/index.js
> +    const curHeight = _wrapperStyle.maxHeight || _wrapperStyle.height
я вот думаю, может для десктопа и для мобилы зададим разные значения maxHeight в стилях, у них как раз разное поведение, десктоп через `Popover` а мобилки через `Drawer` и дровер можно максимально и по шире открыть будет.

@simonprod @cray0000 что думаете?

2020-12-09 01:18 UTC, simonprod commented on packages/ui/components/popups/Dropdown/index.js
> +    if (activePosition >= curHeight - 10) {
погрешность типа, activePosition - это позиция активного элемента по y
было так что я открывал дропдаун, а скролить к активному элементу не хотело, т.к. высота стаяла так, что "кусочек" элемента входил в curHeight (как раз примерно 10 пикселей вроде)
можно даже больше 10 сделать

2020-12-09 01:21 UTC, simonprod commented on packages/ui/components/popups/Dropdown/index.js
> +    const curHeight = _wrapperStyle.maxHeight || _wrapperStyle.height
```stylus
.wrapper
   стили для Popover
   +to(780px)
      стили для Drawer
```

это должно работать, ты же хотел объединить в один проп

2020-12-09 14:08 UTC, cray0000 commented on packages/ui/components/popups/Dropdown/index.js
> +    const curHeight = _wrapperStyle.maxHeight || _wrapperStyle.height
я думаю можно как Семен предложил, ток правильно) через `+from($UI.media.tablet)`, надо просто описать это в ридми, что на десктопе и на мобиле юзаются разные компоненты под аапотом, и что через @media можно дать им разные стили, если хочется.

2020-12-09 14:10 UTC, cray0000 commented on packages/ui/components/popups/Dropdown/index.js
> +    const curHeight = _wrapperStyle.maxHeight || _wrapperStyle.height
у нас помоему даже есть кстати упрощение для медиа всех, просто надо будет заюзать

+tablet()
  стили

2020-12-09 21:20 UTC, pturchik requested changes

2020-12-09 21:20 UTC, pturchik commented on packages/ui/components/popups/Dropdown/Dropdown.ru.mdx
> +Чтобы правильно применять style для каждого варианта, можно использовать миксин `+from`:
давай тогда напишем не +from а +tablet()

2020-12-09 21:20 UTC, pturchik commented on packages/ui/components/popups/Dropdown/Dropdown.ru.mdx
> +## Позиция для Popover
добавишь сразу это же в английскую доку, тут переводить почти нечего?

2020-12-10 15:28 UTC, pturchik approved these changes

2020-12-10 15:28 UTC, merged