[BREAKING]: server-aggregate: change parameters for orm version
startupjs/startupjs pull request #418
Opened 2020-12-10 13:44 UTC by ssstelsss

2020-12-10 13:51 UTC, olvipi commented on docs/migration-guides/0.30.md
> +      openEvents: async (model, params, session) => {
в session только session.userId?

2020-12-10 15:28 UTC, ssstelsss commented on docs/migration-guides/0.30.md
> +      openEvents: async (model, params, session) => {
по сути да

2020-12-10 15:39 UTC, pturchik requested changes

2020-12-10 15:39 UTC, pturchik commented on packages/backend/index.js
>            const globalCollectionName = path.replace(/\.\*$/u, '')
аналогично с предыдущим пр-ом. назови адекватно) зачем эти global

2020-12-10 15:43 UTC, ssstelsss commented on packages/backend/index.js
>            const globalCollectionName = path.replace(/\.\*$/u, '')
done

2020-12-10 15:51 UTC, olvipi commented on docs/migration-guides/0.30.md
> +      openEvents: async (model, params, session) => {
может если userId то его и прокинуть, а если нет то не session а sessions

2020-12-10 21:48 UTC, merged

2020-12-11 14:14 UTC, cray0000 commented on docs/migration-guides/0.30.md
> +      openEvents: async (model, params, session) => {
там еще всякие loggedIn и т.д. есть.