fix(ui -> Tooltip): web event window
startupjs/startupjs pull request #427
Opened 2020-12-11 19:20 UTC by simonprod

2020-12-14 09:21 UTC, ssstelsss approved these changes

2020-12-15 10:14 UTC, pturchik requested changes

2020-12-15 10:14 UTC, pturchik commented on packages/ui/components/Tooltip/Caption/index.web.js
> +  }
тебе по идее надо делать removeEventListener ещё при дестрое компонента

2020-12-15 10:29 UTC, pturchik requested changes

2020-12-15 10:29 UTC, pturchik commented on packages/ui/components/Tooltip/index.styl
> +    overflow visible
а pointer-events none не спасает ?

2020-12-15 10:42 UTC, simonprod commented on packages/ui/components/Tooltip/index.styl
> +    overflow visible
Это чтобы модалка была не на весь экран, точнее я убираю оверлей чтобы можно было скролить/кликать свободно. В тултипе он не нужен

2020-12-15 12:20 UTC, cray0000 commented on packages/ui/components/Tooltip/Caption/index.web.js
> +  }
да, потому что компонент может сдохнуть в момент, когда наведена мышка, и тогда он не потрется, так что надо коллбек в useRef запихивать и потом если он есть в useRef, делать remove при дестрое в каком-нить useEffect, или useLayoutEffect

2020-12-15 14:02 UTC, pturchik commented on packages/ui/components/Tooltip/index.styl
> +    overflow visible
так по идеи если на ней все ивенты убрать и сделать её прозрачной ты через неё и так сможешь кликать. у тебя то внутри все позиционируется относительно модалки, а ты её сжимаешь в точку. я уверен в каких-нибудь браузерах будут проблемы

2020-12-15 16:22 UTC, simonprod commented on packages/ui/components/Tooltip/index.styl
> +    overflow visible
я смотрел на chrome, safari, firefox все гуд

2020-12-16 16:25 UTC, pturchik approved these changes

2020-12-16 16:33 UTC, merged