feat(Docs): Added component search
startupjs/startupjs pull request #448
Opened 2020-12-22 19:09 UTC by olvipi

2020-12-22 19:11 UTC, olvipi commented
![image](https://user-images.githubusercontent.com/46069436/102924404-2cab2c80-449a-11eb-8065-026e7a22b84d.png)

2020-12-22 19:11 UTC, olvipi commented
![image](https://user-images.githubusercontent.com/46069436/102924477-4b112800-449a-11eb-9cb0-b21a0bd115ab.png)

2020-12-23 11:49 UTC, pturchik requested changes

2020-12-23 11:49 UTC, pturchik commented on packages/docs/client/app/Layout/index.js
> +      return item.label.match(new RegExp('^' + value, 'gi'))
может искать нужно не от начала ? просто подстроку в строке чтобы искало

2020-12-23 11:49 UTC, pturchik commented on packages/docs/client/app/Layout/index.js
> +  const [value, setValue] = useState({})
я что-то не пойму что это на состояние такое которое в себе всегда хранит пустой объект с непонятной целью. у тебя же `setValue` нигде не вызывается кроме как в `useEffect`

2020-12-23 11:49 UTC, pturchik commented on packages/docs/client/app/Layout/index.js
> +  const options = Object.entries(docs).reduce((acc, item) => {
опции не вижу чтобы были связаны с набранным текстом в autosuggest.

2020-12-23 11:51 UTC, olvipi commented on packages/docs/client/app/Layout/index.js
> +  const [value, setValue] = useState({})
это что бы сбросить состояние Autosuggest при смене роута и завкрыть поповер

2020-12-23 11:52 UTC, olvipi commented on packages/docs/client/app/Layout/index.js
> +  const options = Object.entries(docs).reduce((acc, item) => {
autosuggest фильтрует дату под капотом

2020-12-23 11:54 UTC, olvipi commented on packages/docs/client/app/Layout/index.js
> +      return item.label.match(new RegExp('^' + value, 'gi'))
c 58 по 64 строку это временный хак до фикса высоты Slicer, после фикса их надо удалить

2020-12-23 11:54 UTC, olvipi commented on packages/docs/client/app/Layout/index.js
> +      return item.label.match(new RegExp('^' + value, 'gi'))
сначала для дублирования логики Autosugest

2020-12-29 09:43 UTC, closed without merging