feat(APP): changed errors catch
startupjs/startupjs pull request #473
Opened 2021-01-12 09:37 UTC by ssstelsss

2021-01-13 08:13 UTC, ssstelsss commented on packages/app/README.md
> +          </Div>
потому что опенсурс либа и код должен быть понятен большинству пользователей. А паг скорее локальное решение

2021-01-13 08:22 UTC, lupenq approved these changes

2021-01-13 15:05 UTC, olvipi approved these changes

2021-01-16 04:36 UTC, cray0000 commented on packages/app/README.md
> +          </Div>
я добавлю автокомпиляцию pug'a в примерах на jsx, и можно будет глобально переключаться на сайте между pug и jsx, так что можешь на pug писать примеры

2021-01-16 04:38 UTC, cray0000 commented on packages/app/README.md
> +          </Div>
а, это ридми самого пакета, а не mdx документация. Это должно быть на чистом jsx, да)

2021-01-16 04:44 UTC, cray0000 approved these changes

2021-01-20 07:33 UTC, lupenq approved these changes

2021-01-21 03:10 UTC, cray0000 requested changes

2021-01-21 03:10 UTC, cray0000 commented on packages/orm/lib/promisifyRacer.js
> +        if (err.code.includes('ERR_ACCESS')) {
.includes есть только у строки. И err.code вообще может не быть. Проверяй сначала typeof err.code === 'string'

2021-01-25 07:55 UTC, ssstelsss commented on packages/orm/lib/promisifyRacer.js
> +        if (err.code.includes('ERR_ACCESS')) {
done

2021-01-25 12:54 UTC, cray0000 approved these changes

2021-01-25 19:16 UTC, pturchik requested changes

2021-01-25 19:16 UTC, pturchik commented on packages/app/client/Router/Error/index.js
> +          goBack=()=>history.goBack()
space

2021-01-25 19:16 UTC, pturchik commented on packages/app/client/Router/index.js
> +      Error(value=err pages=errorPages disableError=()=>setErr())
space

2021-01-25 19:16 UTC, pturchik commented on packages/app/client/Router/Error/templates/AccessDeny/index.js
> +        H3.info 403: Permission denied
а почему нельзя было использовать title, description, children лаяута а самому верстать здесь нужно?

2021-01-25 19:16 UTC, pturchik commented on packages/app/client/Router/Error/index.js
> +          goBack=()=>history.goBack()
я думаю можно goBack и не кидать а просто во вьюхе кому надо воспользуется хуком useHistory сам

2021-01-25 19:16 UTC, pturchik commented on packages/app/README.md
> +If you don't pass this props, then the default template will be renderd.
renderEd

2021-01-25 19:25 UTC, pturchik commented
я думаю что ErrorPages вообще можно вынести из роутера куда-то наверх и без всяких disableError. тупо кидать функцию reload если надо, которая просто перезагрузит страницу/приложение
@cray0000 @ssstelsss что думаете?

2021-01-25 20:05 UTC, cray0000 commented
ну роутер все равно внутри app, так что не важно где он там валяется. Можно вынести повыше, если хотите, но я разницы не вижу особой.

А по поводу того как именно `errorPages` указывать кастомные при вызове `<App />` -- вроде ща все довольно очевидно выглядит, так что разве что по мелочам апи менять. Насчет goBack - думаю да, если кастомные предоставляют компоненты, то уже в нем и могут заюзать `useHistory` сами

2021-01-26 13:55 UTC, ssstelsss commented on packages/app/client/Router/Error/templates/AccessDeny/index.js
> +        H3.info 403: Permission denied
done

2021-02-01 08:52 UTC, pturchik requested changes

2021-02-01 08:52 UTC, pturchik commented on packages/app/README.md
>        //   ...,
убери запятую в коцне

2021-02-01 08:52 UTC, pturchik commented on packages/app/README.md
> +            <Button onPress={() => history.goBack()}>Go back</Button>
history надо бы достать, а лучше даже если это выделишь в отдельный jsx блок где ты создаешь компоненту а потом сюда прокидываешь. самое главное ты проверял что так будет работать хук useHistory к примеру и не выкидывать никаких warning ?

2021-02-01 08:52 UTC, pturchik commented on packages/app/client/Router/Error/templates/AccessDeny/index.js
> +      )
spaces
```js
ErrorTemplate(
  title=...
  ...
)

2021-02-01 08:59 UTC, pturchik requested changes

2021-02-01 08:59 UTC, pturchik commented on packages/app/client/Router/Error/templates/ErrorTemplate/index.js
> +  const [{ supportEmail } = {}] = useSession('criticalVersion.meta')
откуда `supportEmail` в `criticalVersion.meta` ? откуда вообще `criticalVersion` в `session` ? я не увидел в коде чтобы оно туда ложилось

2021-02-01 08:59 UTC, pturchik commented on packages/app/client/Router/Error/templates/ErrorTemplate/index.js
> +        if supportEmail && isSupportEmailBlock
не нужно `isSupportEmailBlock` никакой, если `supportEmail` есть, значит показываем.

2021-02-01 10:20 UTC, pturchik requested changes

2021-02-01 10:20 UTC, pturchik commented on packages/app/README.md
> +You can just change the `text` and `onPress` function on the default error template to output to other code, for example.
Давай как-то в повествовательном стиле напишем, чем сразу терминами грузить
Примерно как-то так, поправь если там где-то упустил

### Display an error

You can change the error page to your own by passing an object of the following structure to the "errorPages" property:
- `ERROR_KEY (Component)`: specific page for `ERROR_KEY`
- `default (Component)`:  the page that will be used when there is no specific page for the `ERROR_KEY`

To show an error page, use `emit('error', ERROR_KEY)`, where `ERROR_KEY` is the unique identifier of the error.
To hide an error page when the error occurred, use `emit('error') - emit('error', '')`. - только проверь что работает первый вариант.

2021-02-01 10:20 UTC, pturchik commented on packages/app/README.md
> +You can just change the `text` and `onPress` function on the default error template to output to other code, for example.
и подогнать нужно как-то под это код немного.

```js
if err
  = errorPages(err || 'default') || ErrorPage - или лучше это инкапуслировать в `Error` компоненте по выборке того что отобразить
```

2021-02-01 10:20 UTC, pturchik commented on packages/app/client/Router/Error/templates/ErrorTemplate/index.js
> +        if supportEmail && isSupportEmailBlock
причем как-то надо показать так не завязываясь на `description`, потому что не всегда в `description` у людей будет текст в конце их дескрипшена `please contact support`

2021-02-01 10:20 UTC, pturchik commented on packages/app/client/Router/Error/templates/ErrorTemplate/index.js
> +        Button.backButton(icon=faArrowLeft onPress=goBack) Go back
сделай здесь свою кнопку `goBack` использующую `emit('error')`. это ведь шаблон наш - и нас такая структура вывода устраивает. кому не понравится верстают свою не используя наш шаблон

2021-02-08 09:00 UTC, pturchik requested changes

2021-02-08 09:07 UTC, pturchik requested changes

2021-02-08 09:07 UTC, pturchik commented on packages/app/client/Router/Error/templates/AccessDeny/index.js
> +      )
что-то не так с отступами

2021-02-08 09:07 UTC, pturchik commented on packages/app/client/Router/Error/templates/DefaultError/index.js
> +      )
что-то не так с отступами

2021-02-08 09:07 UTC, pturchik commented on packages/app/README.md
> +        title={'405: My custom error'}
что-то не так с отступами

2021-02-08 09:07 UTC, pturchik commented on packages/app/README.md
> +You can just change the `text` and `onPress` function on the default error template to output to other code, for example.
не пойму к чему этот текст. `text`, `onPress` не вижу чтобы можно было изменять.

2021-02-08 09:07 UTC, pturchik commented on packages/app/README.md
> +You can just change the `text` and `onPress` function on the default error template to output to other code, for example.
может её просто удалить?
на примере с new error и так в принципе видно что и как, единственное там докинь `supportEmail` чтобы было понятно что его можно кидать тоже.

2021-02-08 09:46 UTC, ssstelsss commented on packages/app/client/Router/Error/templates/ErrorTemplate/index.js
> +
Done

2021-02-08 09:46 UTC, ssstelsss commented on packages/app/README.md
> +You can just change the `text` and `onPress` function on the default error template to output to other code, for example.
done

2021-02-08 09:46 UTC, ssstelsss commented on packages/app/README.md
> +        title={'405: My custom error'}
done

2021-02-08 09:46 UTC, ssstelsss commented on packages/app/client/Router/Error/templates/AccessDeny/index.js
> +      )
done

2021-02-08 09:46 UTC, ssstelsss commented on packages/app/client/Router/Error/templates/DefaultError/index.js
> +      )
done

2021-02-08 09:46 UTC, ssstelsss commented on packages/app/client/Router/Error/index.js
> +  const status = value
done

2021-02-08 11:14 UTC, merged