feat(auth): customization
startupjs/startupjs pull request #525
Opened 2021-02-15 13:18 UTC by lilhakk

2021-02-17 15:43 UTC, vladagurets commented on packages/auth-local/client/components/LoginForm/index.js
> +  onChangeSlide
надо добавить в changelog все breraking ченджи

2021-02-17 15:43 UTC, vladagurets commented on packages/auth-local/client/components/LoginForm/index.js
> -  config,
в конфиге были проперти, которые уже используют в других проектах
к примеру initState для автофилла
используется в Payteam

2021-02-17 15:43 UTC, vladagurets commented on packages/auth-local/client/components/LoginForm/index.js
> +  onChangeSlide
переименовал onChangeAuthPage в onChangeSlide - это, вроде, публичное свойство, если не ошибаюсь

2021-02-17 15:43 UTC, vladagurets commented on packages/auth-local/client/components/LoginForm/index.js
> +      fullSchema = fullSchema.keys(validateSchema)
Так нельзя?

const schema = commonSchema.keys(validateSchema || {})

2021-02-17 15:43 UTC, vladagurets commented on packages/auth-local/client/components/RegisterForm/index.js
> +  validateSchema,
а почему properties и validateSchema - по разным пропсам?
по факту, у каждого поля должно быть проперти о его валидации

2021-02-17 15:43 UTC, vladagurets commented on packages/auth-local/client/components/RegisterForm/index.js
> +      fullSchema = fullSchema.keys(validateSchema)
тот же вопрос - нельзя ли в одну строку?

2021-02-17 15:43 UTC, vladagurets commented on packages/auth/client/components/AuthForm/index.js
> +        H5.caption= DEFAULT_FORMS_CAPTIONS[slide]
а как теперь тайтлы и дескрипшны кастомить?
пейтим юзает это дело

2021-02-18 11:47 UTC, lilhakk commented on packages/auth/client/components/AuthForm/index.js
> +        H5.caption= DEFAULT_FORMS_CAPTIONS[slide]
через renderForm можно

2021-02-18 11:48 UTC, lilhakk commented on packages/auth-local/client/components/LoginForm/index.js
> +      fullSchema = fullSchema.keys(validateSchema)
надо проверить, у joi там свои объекты

2021-02-18 11:51 UTC, lilhakk commented on packages/auth-local/client/components/LoginForm/index.js
> -  config,
надо бы глянуть как оно реализовано, я убрал config, т.к. в нем в основном переопределяются текста разные, собственно щас все можно переверстать через renderForm. initState пока не понятно где и как юзается

2021-02-18 11:52 UTC, lilhakk commented on packages/auth-local/client/components/LoginForm/index.js
> +  onChangeSlide
у нас там changelog вроде сам генерится, или все равно как раньше в migration guide нужно добавлять?

2021-02-18 16:30 UTC, cray0000 commented on packages/auth-local/client/components/LoginForm/index.js
> +  onChangeSlide
если есть breaking, то надо в next делать PR. И надо в описании PR писать BREAKING CHANGES: и там описывать ниже что поменялось и как мигрировать код на новую версию

2021-02-19 10:29 UTC, vladagurets commented on packages/auth-local/client/components/LoginForm/index.js
> -  config,
да-да, теперь все можно кастомить через твои properties
все, кроме хединг текстов, на сколько я понял

2021-02-19 19:13 UTC, lilhakk commented on packages/auth-local/client/components/LoginForm/index.js
> +      fullSchema = fullSchema.keys(validateSchema)
с пустым объектом не хочет мержиться

2021-02-20 23:15 UTC, cray0000 commented
я обновил ветку `next`, чтобы код был последний. Кстати в будущем, если видите, что `next` отстал от мастера, то мерджите руками master в next и пуште, чтобы код актуальный был в PR

2021-02-22 06:59 UTC, lilhakk commented
@cray0000 там на одном проекте нужно инитить value в поля сразу, я сделал вот так, чтобы в properties по мимо полей можно было писать и value:
```js
email: {
  value: 'example@gmail.com',
  label: 'Email'
}
```
https://github.com/startupjs/startupjs/pull/525/files#diff-9aa3c3d4f7278d4eeaf12aa99307393f08aab190074b766839fe1b28f2e7a288R36

Насколько это валидно и не поломает там ничего useMemo?

@cray0000, @vladagurets избавился от компонента SuccessRedirect (нужен был для редиректа после после релоада приложухи) таким образом:
https://github.com/startupjs/startupjs/pull/525/files#diff-ec4d26d0156e659d449a8c3dc57028eb9c617e0b1b279ee81e1b82727395c815R10

Раньше чтобы сессия обновилась - нужно было перезагрузить страницу, я помню что когда мы пилили проект на чистом реакте, у нас был роут get-me, там так же были сессии и они в куки ложились (на мобиле куки не реализованы как я понял), собственно после логина мы дергали роут этот и обновляли сессии.
Опять же вопрос насколько валидно это для startupjs? И там кстати для logout можно сделать похожим образом, но для logout, наверное, релоад более логичен.

2021-02-22 11:28 UTC, vladagurets approved these changes

2021-02-22 11:31 UTC, vladagurets commented
@lilhakk 
Если честно - вообще не помню юзкейс SuccessRedirect
думаю что о нем забыли, пережитки прошло
так что гуд что убрал

по поводу этого `Раньше чтобы сессия обновилась - нужно было перезагрузить страницу, я помню что когда мы пилили проект на чистом реакте, у нас был роут get-me, `
сейчас эта логика под капотом app компонента: [LINK](https://github.com/startupjs/startupjs/blob/204ffa5b5e177117db1420dd0e8547cd91814146/packages/app/client/index.js#L107)

2021-02-22 11:46 UTC, lilhakk commented
@vladagurets да я этот код и нашел, но сама сессия щас, обновляется только когда релоадишь приложение. Я добавил тот же запрос, только уже после авторизации, чтобы в _session добавить новые данные

2021-02-25 09:13 UTC, pturchik requested changes
move set defaults to form component

2021-02-26 14:40 UTC, pturchik requested changes

2021-02-26 14:40 UTC, pturchik commented on packages/auth/client/helpers/finishAuth.js
> +  if (Platform.OS !== 'web') {
why exclude web platform ?

2021-03-02 19:31 UTC, pturchik requested changes

2021-03-02 19:31 UTC, pturchik commented on packages/app/server/sessionMiddleware.js
> +  if (!restoreUrl || req.url !== '/api/serverSession') return next()
выглядит немножко как хак) засунь тогда просто эту логику в api/serverSession и норм

2021-03-03 13:36 UTC, merged