feat(e2e): improve Detox
startupjs/startupjs pull request #559
Opened 2021-03-10 14:26 UTC by lupenq

feat(e2e): improve Detox and add screenshots match
test(ui/Button): add Button tests

2021-03-10 14:40 UTC, ssstelsss commented on packages/docs/client/app/Layout/index.js
> +      renderItema=item => renderItem(item, pathname)
renderItema точно нет ошибки в названии?

2021-03-10 14:41 UTC, lupenq commented on packages/docs/client/app/Layout/index.js
> +      renderItema=item => renderItem(item, pathname)
есть

2021-03-10 14:42 UTC, ssstelsss commented on packages/e2e/README.md
> +## Скриншот тестирование
наверное тут на английском

2021-03-10 14:46 UTC, ssstelsss commented on packages/e2e/init.js
> +    'xcrun simctl status_bar "iPhone 11" override --time "12:00" --batteryState charged --batteryLevel 100 --wifiBars 3 --cellularMode active --cellularBars 4'
нужно проверить для тестов которые длятся больше минуты, будет ли меняться время в процессе работы

2021-03-10 14:50 UTC, ssstelsss commented on packages/ui/docs/foundation/testing.en.mdx
> +## Скриншот тестирование
same

2021-03-10 14:51 UTC, ssstelsss commented on packages/ui/docs/foundation/testing.ru.mdx
>  Для e2e тестирование на мобильных платформах используется библиотека [Detox](https://github.com/wix/Detox) и test-runner [Jest](https://jestjs.io/)
тестирования

2021-03-10 14:54 UTC, lupenq commented on styleguide/e2e/Button.e2e.js
> +    await x('#disabledButton').tap()
тут тест дописываю

2021-03-10 14:56 UTC, lupenq commented on packages/e2e/README.md
> +## Скриншот тестирование
Да

2021-03-11 10:37 UTC, cray0000 approved these changes

2021-03-11 10:37 UTC, cray0000 commented on styleguide/e2e/Button.e2e.js
> +const x = require('@startupjs/e2e/helpers')
а нельзя реэкспортить `x` в основном `@startupjs/e2e`?

2021-03-11 10:49 UTC, cray0000 requested changes

2021-03-11 10:49 UTC, cray0000 commented on styleguide/main/pages/PTestComponent/testComponents.js
> +export { default as ButtonTests } from '@startupjs/ui/components/Button/tests'
здесь под таким же названием и реэкспорти - просто `Button`, а не `ButtonTests`

2021-03-11 10:49 UTC, cray0000 commented on styleguide/main/pages/PTestComponent/index.js
> +import { ButtonTests } from './testComponents'
`import * as testComponents from ...`

2021-03-11 10:49 UTC, cray0000 commented on styleguide/main/pages/PTestComponent/index.js
> +    switch (componentName) {
возвращать паг и рендерить функцию тут не надо. Просто верни сам компонент и его же и отрендери ниже. И бери его из testComponents по названию прост

```
const Component = testComponents[componentName]
if (!Component) throw Error(`No tests for component ${componentName} found!`)
return Component
```

2021-03-11 10:49 UTC, cray0000 commented on styleguide/main/pages/PTestComponent/index.js
> +
здесь просто

`const Component = getComponent()`

и ниже в pug просто вызывай по-обычному Component без всяких интерполяций

2021-03-11 11:04 UTC, cray0000 requested changes

2021-03-11 11:04 UTC, cray0000 commented on packages/ui/components/Button/tests/index.js
> +import React, { useState } from 'react'
давай назовем папку `__tests__`, чтобы сразу было очевидно, что она не касается основного кода и чисто сервисная.

И прямо в эту папку и запихни еще и сам файл с тестами `index.e2e.cjs` (скорее всего именно явно тут `.cjs` надо, потому что вокруг весь код ESM-ный в самом пакете `ui`)

И в `styleguide/e2e/index.e2e.js` просто реквайри этот файл.

2021-03-11 11:23 UTC, lupenq commented on styleguide/e2e/Button.e2e.js
> +const x = require('@startupjs/e2e/helpers')
Не получается, потому что глобального контекста детокса нет в момент require файла с функцией x

2021-03-11 11:24 UTC, cray0000 commented on styleguide/e2e/Button.e2e.js
> +const x = require('@startupjs/e2e/helpers')
ясно, ок

2021-03-11 11:26 UTC, cray0000 commented on styleguide/e2e/Button.e2e.js
> +const x = require('@startupjs/e2e/helpers')
тогда сразу сделай чтобы экспортилось не как дефолт, а как именованное, чтобы было

```
const { x } = require(...)
```

а то выходит что из файла с названтем `helpers` чисто экспортится только один хэлпер и все. А в будущем может еще какие-то хелперы появятся

2021-03-11 17:27 UTC, cray0000 approved these changes

2021-03-12 08:40 UTC, ssstelsss approved these changes

2021-03-12 09:04 UTC, merged