feat(recaptcha): Add @startupjs/recaptcha package
startupjs/startupjs pull request #579
Opened 2021-03-24 13:43 UTC by lupenq

2021-03-24 13:51 UTC, ssstelsss commented on packages/recaptcha/README.md
> +    "RECAPTCHA_SECRET_KEY": "ВАШ_СЕКРЕТНЫЙ_КЛЮЧ"
YOUR_SECRET_KEY

2021-03-24 13:56 UTC, ssstelsss commented on packages/recaptcha/README.md
> +## Параметры
Parameters

2021-03-24 13:56 UTC, ssstelsss commented on packages/recaptcha/README.md
> + - `size` [String] - The size of the widget (`invisible`, `normal` или `compact`). Default: `invisible`
or

2021-03-24 13:56 UTC, ssstelsss commented on packages/recaptcha/README.md
> + - `theme` [String] - The color theme of the widget (`dark` или `light`). Default: `light`
or

2021-03-24 14:00 UTC, ssstelsss commented on packages/recaptcha/client/Recaptcha/get-template.js
> +            .container {
а почему .container два раза?

2021-03-24 14:27 UTC, ssstelsss commented on packages/recaptcha/client/Recaptcha/index.web.js
> +    }
if (!ready) {
  setReadyInterval(setInterval(_updateReadyState, 1000))
}

2021-03-24 14:41 UTC, ssstelsss commented on packages/recaptcha/client/Recaptcha/index.web.js
> +      setReady(true)
setReadyInterval()

2021-03-24 15:05 UTC, ssstelsss approved these changes

2021-03-25 06:05 UTC, cray0000 requested changes

2021-03-25 06:05 UTC, cray0000 commented on packages/recaptcha/client/Recaptcha/index.js
> +          const { data } = await axios.post('/api/recaptcha-check-token', {
вот это бессмысленно. Так у тебя нет никакой защиты данных.

Потому что никакой проверки на сервере на самом деле выходит вообще не происходит.

Капча нужна для того, чтобы сгенерить токен, который подтвердит отправку каких-то данных POST-запросом на сервер. И чтобы сервер авторизовал этот POST запрос, так же, как мы авторизуем запросы, проверяя, что юзер залогинен, или что у него есть необходимая роль.

А у тебя выходит, что сначала типа капча проверяется сама по себе на сервере отдельным запросом и все. И это чисто что-то разрешает сделать дальше на клиенте. Например, разрешает нажать на кнопку Submit. НО! А дальше что? Дальше просто чувак нажимает на Submit и отправляется форма с данными?

А где проверка на самое необходимое? Где проверка что данные формы заполнил не робот, а человек?

1. Любой клиентский код может быть изменен элементарно через консоль или через плагины хрома, и кнопка Submit может включаться сразу, не дожидаясь ответа от сервера с проверкой.

2. А вообще мне, как хакеру, даже не надо будет париться с твоим клиентским кодом. Я просто посмотрю во вкладке Network тупо по какой URL-ке ты потом отправляешь POST запрос с данными о регистрации пользователя и я тупо напишу бота, который вообще не будет через браузер что-либо делать. А просто будет втупую посылать напрямую POST запросы с нужными мне данными на сервер. И я тебе еще быстрее и вообще не парясь позарегиваю миллионы спам-аккаунтов и сломаю твой сайт еще быстрее и проще.

Потому что сами данные формы ты будешь посылать потом отдельным запросом, уже после проверки капчи. А значит проверка капчи у тебя тупо ради самого факта проверки капчи. Она абсолютно бессмысленная.

Апи твоего компонента должно быть такое:

`onVerify` просто вызывается с токеном. И дальше уже юзер должен взять этот токен и отправить его вместе со своей формой с какими-то полезными данными на сервер.

И на сервере юзер сам должен провалидировать, что токен верный, а потом уже начать обрабатывать полезные данные.

То есть часть твоего апи будет твой метод `checkToken` на сервере.

Люди будут юзать и клиентский компонент Recaptcha, чтобы получить токен, и дальше обязательно будут юзать `checkToken` на сервере, чтобы его проверить, отправив токен ВМЕСТЕ с полезными данными, валидность которых им и надо проверить.

2021-03-25 06:22 UTC, cray0000 commented on packages/recaptcha/client/Recaptcha/index.js
> +          const { data } = await axios.post('/api/recaptcha-check-token', {
`/api/recaptcha-check-token` вообще надо убрать в итоге, сама по себе отдельная проверка капчи, без связки с какими-то полезными данными, не имеет смысла

2021-03-26 12:03 UTC, ssstelsss approved these changes

2021-03-31 15:24 UTC, pturchik requested changes

2021-03-31 15:24 UTC, pturchik commented on packages/recaptcha/server/middlewares/setRecaptchaSiteKey.js
> +  const RECAPTCHA_SITE_KEY = nconf.get('RECAPTCHA_SITE_KEY')
может стоит проверить что он есть ? если эта мидлвара подключена а ключа нет то либо не сетить и писать какой-то лог ЧТО НЕ НАЙДЕНО либо ошибку кидать прям

2021-04-01 09:51 UTC, merged