fix(avatar): fix size prop
startupjs/startupjs pull request #590
Opened 2021-04-01 10:02 UTC by shir-dm

2021-04-02 13:25 UTC, pturchik requested changes

2021-04-02 13:25 UTC, pturchik commented on packages/ui/components/Avatar/index.js
> +    PropTypes.oneOf(['l', 'm', 's']),
давай писать от меньшего к большему 's', 'm', 'l'

2021-04-02 13:25 UTC, pturchik commented on packages/ui/components/Avatar/index.js
> +  const avatarStyleForSize = typeof size === 'number'
смотри, мы стили называем немного по-другому в js'е. avatarStyle, avatarWrapperStyle - ${элемент_которому_принадлежит_стиль}Style.

2021-04-02 13:25 UTC, pturchik commented on packages/ui/components/Avatar/index.js
> +  const styleForRoot = Array.isArray(style) ? [...style, avatarStyleForSize] : { ...style, ...avatarStyleForSize }
посмотри как работает `StyleSheet.flatten` и используй

2021-04-02 13:25 UTC, pturchik commented on packages/ui/components/Avatar/index.js
> +      style= styleForRoot
пробелы не ставим после = в свойствах

2021-04-02 13:25 UTC, pturchik commented on packages/ui/components/Avatar/index.js
> +    : {}
ты можешь заэкспортить `$this` из стилей здесь написать одну логику для размеров а не разбросать по стилям и js'у

```styl
:export
  config: $this
```

```js
import STYLES from './index.styl

const { config } = STYLES
...
export default observer(function Avatar () {
  const _size = config.avatarSizes[size] || size
  const avatarStyle = { width: _size, height: _size }
})
```

ещё было бы хорошо если бы ты занес переменные размеров в конфиг

```styl
$this = merge({
  avatarSizes: {
    s: ..,
    ...
  },
  statusSizes: { ... }
},
  $UI.Tag,
  true
)
```

2021-04-02 13:25 UTC, pturchik commented on packages/ui/components/Avatar/index.js
> +    : {}
тогда тебе не понадобится все эти модификаторы тут на `size`

2021-04-05 12:29 UTC, pturchik requested changes

2021-04-05 12:29 UTC, pturchik commented on packages/ui/components/Avatar/index.js
> +  const _size = `${config.avatarSizes[size] || size}px`
тебе не нужно писать `px`. почитай о react-native на офциальном сайте, он воспринмает обычные числовые значения как пиксели

2021-04-05 12:29 UTC, pturchik commented on packages/ui/components/Avatar/index.js
> +        Div.status(styleName=[status, shape, _styleName] style=statusStyle)
зачем тебе модификатор _styleName?

2021-04-05 12:29 UTC, pturchik commented on packages/ui/components/Avatar/index.js
> +            styleName=_styleName
тебе теперь не нужен этот модификатор, он не используется

2021-04-05 12:29 UTC, pturchik commented on packages/ui/components/Avatar/index.js
> +            Span.fallback(styleName=_styleName bold)
тебе по идеи бы и шрифт для фалбэка в зависимости от size рута вычислять примерный когда size не s, m, l

2021-04-06 08:45 UTC, pturchik commented
а залей скрины посмотреть для размера аватарки 50 100 150 200 250

2021-04-06 10:45 UTC, shir-dm commented
![Снимок экрана от 2021-04-06 15-44-23](https://user-images.githubusercontent.com/78920501/113699546-265e5a80-96ef-11eb-9fe2-e6799511fe00.png)
![Снимок экрана от 2021-04-06 15-45-24](https://user-images.githubusercontent.com/78920501/113699552-28281e00-96ef-11eb-88ed-f0ed4d411053.png)

2021-04-06 12:50 UTC, merged