feat(auth): implement recaptcha in register and reset forms
startupjs/startupjs pull request #596
Opened 2021-04-02 13:30 UTC by lupenq

2021-04-02 13:52 UTC, ssstelsss approved these changes

2021-04-05 15:49 UTC, lilhakk commented on packages/auth-local/client/components/RecoverForm/index.js
> +  function onSubmit (recaptchaToken) {
Не совсем понятно как в onSubmit попадает recaptchaToken, там под капотом что-то капча делает?

2021-04-05 15:52 UTC, lupenq commented on packages/auth-local/client/components/RecoverForm/index.js
> +  function onSubmit (recaptchaToken) {
Этот пр снова WIP сейчас :)

onSubmit в предыдущем коммите получал токен, уже не получает, уберу.

2021-04-05 15:52 UTC, lupenq commented on packages/auth-local/client/components/RecoverForm/index.js
> +  function onSubmit (recaptchaToken) {
Этот пр снова WIP сейчас :)

onSubmit в предыдущем коммите получал токен, уже не получает, уберу.

2021-04-06 12:10 UTC, pturchik requested changes

2021-04-06 12:16 UTC, lupenq commented on packages/auth/server/initAuth.js
> +        ...$session.get()
по примеру: https://github.com/startupjs/startupjs/blob/e7afe44238367d718eb9a4f106f12ec314113a80/packages/auth/server/initAuth.js#L64

2021-04-06 12:17 UTC, lupenq commented on packages/auth/server/initAuth.js
> +        ...$session.get()
по примеру: https://github.com/startupjs/startupjs/blob/e7afe44238367d718eb9a4f106f12ec314113a80/packages/auth/server/initAuth.js#L64

2021-04-07 08:24 UTC, merged