fix(typography): add custom fonts
startupjs/startupjs pull request #597
Opened 2021-04-05 10:52 UTC by shir-dm

2021-04-05 15:08 UTC, lilhakk commented on packages/ui/styles/typography.styl
> +    _result+='Black'
Что если хранить эти значения в объекте:

```
$weightConstants = { '100': 'Thin', '200': 'ExtraLight' }

fontFamily(_fontName, _fontWeight, _fontStyle = '')
  _result = _fontName + '-' + $weightConstants[_fontWeight]
  _result += _fontStyle

  font-family _result

.test
  fontFamily('Roboto', '100')
```

2021-04-06 06:35 UTC, shir-dm commented on packages/ui/styles/typography.styl
> +    _result+='Black'
переделал, но немного по другому, чтобы сохранить weight числом

2021-04-06 08:43 UTC, pturchik requested changes

2021-04-06 08:43 UTC, pturchik commented on packages/ui/styles/typography.styl
> +      _resultFontWeight = value
зачем тебе цикл для поиска значения? ты можешь просто взять его из констант.

$fontWeightNamesMap = {
  100: '...',
  200: '...'
}

$defaultFontWeight = 400

```styl
fontFamily(name, weight, style) {
  name = $fontWeightNamesMap[weight] || $fontWeightNames[defaultFontWeight]
  ...
}
```

2021-04-06 08:43 UTC, pturchik commented on packages/ui/components/typography/Typography.en.mdx
> +To use custom fonts, you need to use mixin `fontFamily (fontName, fontWeight, fontStyle)`:
`fontFamily(...)`

2021-04-06 08:43 UTC, pturchik commented on packages/ui/components/typography/Typography.en.mdx
> +To add custom fonts, add them to the public / fonts folder and type `yarn fonts` in the console. The name of the font files must be in accordance with the Google Fonts rules - `{font name} - {Thickne
`{Font name}-{Thickness}{Style}` зачем пробелы?

2021-04-07 08:41 UTC, lilhakk approved these changes

2021-04-08 10:44 UTC, cray0000 requested changes

2021-04-08 10:44 UTC, cray0000 commented on packages/ui/components/typography/Span/index.styl
> +  fontFamily('Roboto', 400)
дефолтные шрифты менять не будем в нашем фреймворке, пусть будут стандартные для ios, android и для web'a. Мы с @pturchik обсуждали какие оставить стандартные системные шрифты, узнай у него.

2021-04-15 07:06 UTC, pturchik requested changes

2021-04-15 07:06 UTC, pturchik commented on packages/ui/components/typography/Span/index.styl
> +    &.{variant}
это решение проблемы в лоб. ты можешь накинуть какой нибудь модификатор в js'е normal, heading и по нему вешать fontFamily

2021-04-20 07:17 UTC, pturchik requested changes

2021-04-20 07:17 UTC, pturchik commented on packages/ui/styles/variables.styl
> +$UI.fontHeading = "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Ubuntu, 'Helvetica Neue', sans-serif"
тебе не нужно из засовывать в $UI, это должны быть локальные переменные. иначе их подменят и вся твоя логика может не правильно работать.

```styl
$fontNormal = "..."
$fontHeading = "..."

$UI.fontFamilies = merge({
  normal: $fontNormal,
  heading: $fontHeading
}, $UI.fontFamilies, true)
```

в принципе можно тоже самое проделать и с fontWeight. 
```styl
$fontWeightNormal = 400
$fontWeightHeading = 700

$UI.fontWeight = merge(...)
```

2021-04-20 07:17 UTC, pturchik commented on packages/ui/styles/typography.styl
> +    if (!isCustomFont(_fontName))
`if (isCustomFont(...)) { ..} else { ... }`

зачем изначально называться функцию так чтобы потом приходилось делать её отрицание и человек который будет читать код должен это в голове так скажем двойное отрицание представить. называй уже isDefaultFont или isCustomFont и внутри функции напиши условия без !

2021-04-26 22:43 UTC, pturchik requested changes

2021-04-26 22:43 UTC, pturchik commented on packages/ui/components/typography/Typography.ru.mdx
> +Для добавления кастомных шрифтов, их необходимо добавить в папку public/fonts и набрать в консоли `yarn fonts`. Название файлов шрифтов должно быть в соответстии с правилама Google Fonts - `{название
давай вынесем в отдельный пункт меню "Шрифты".
напишем там о том что для обычного текста и заголовков используются системные шрифты "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Ubuntu, 'Helvetica Neue', sans-serif", о том что ты можешь поменять шрифт это используя `$UI.fontFamilies.normal`, `$UI.fontFamilies.heading` и пример привести как это сделать, можно так же написать что вы можете добавить любую свою переменную сюда с именем шрифта к примеру `$UI.fontFamilies.myFontName`, далее напишем про миксин `fontFamily`, о том что в него нужно кидать имена ('normal', 'heading', 'myFontName') с примером, потом напишем о том что как добавлять кастомные шрифты и затем чтобы его использовать прописать в `$UI.fontFamilies.normal` или куда-то ещё, так как компоненты `Span`, `H1-H6` ориентируются на эти переменные, напишем о том что для кастомных шрифтов чтобы миксин `fontFamily` работал нужно прописать их в `$UI.customFontFamilies = ['CosmicSans', 'Roboto', ...]` а в `$UI.fontFamilies.*` только одно название кастомного шрифта допустимо указывать. 

в общем поколдуй над текстом

2021-05-04 08:40 UTC, merged