feat(notification): add notification package
startupjs/startupjs pull request #603
Opened 2021-04-06 15:49 UTC by ssstelsss

Docs in progress

2021-04-08 15:29 UTC, lupenq requested changes

2021-04-08 15:29 UTC, lupenq commented on packages/notification/.eslintrc.json
> +{
Думаю этот файл лишний

2021-04-08 15:29 UTC, lupenq commented on packages/notification/README.md
> +```js
sh

2021-04-08 15:29 UTC, lupenq commented on packages/notification/README.md
> +  import app from '../app.json'
лишнее

2021-04-08 15:29 UTC, lupenq commented on packages/notification/README.md
> +In `root/index.js` add `initOneSignal`:
Root

2021-04-08 15:29 UTC, lupenq commented on packages/notification/README.md
> +- `initOneSignal(useInit)` - `useInit` - the function that will be called after registering the application, here you can place functions from the(https://documentation.onesignal.com/docs/react-nativ
Забыл вставить название ссылки

2021-04-08 15:29 UTC, lupenq commented on packages/notification/docs/notification.ru.mdx
> +  Для настройки Android необходимо получить и зарегестрировать в `OneSignal` [Firebase Server Key](https://documentation.onesignal.com/docs/generate-a-google-server-api-key). Выполните шаги в соответ
соответствии

2021-04-08 15:29 UTC, lupenq commented on packages/notification/docs/notification.ru.mdx
> +Эти ключи можно найти на в настройках вашего приложения [на сайте onesignal](https://app.onesignal.com/apps). Для этого:
найти в настройках

2021-04-08 15:29 UTC, lupenq commented on packages/notification/docs/notification.ru.mdx
> +При первом запуске приложения будет сгенерирован уникальный `id` в `onesignal`  для пользователя (посмотреть их можно в разделе `Audience` [вашего приложения в onesignal](https://app.onesignal.com/ap
удобно, так

2021-04-08 15:29 UTC, lupenq commented on packages/notification/docs/notification.ru.mdx
> +Протестировать работу нотификаций для iOS можно только на реальном устройстве. Важный момент заключается в том, что устройство на котором будет производиться тестирование и компьютер должны находитьс
адрес

2021-04-08 15:29 UTC, lupenq commented on packages/notification/package.json
> +  "version": "0.33.4",
34 уже можно)

2021-04-08 15:29 UTC, lupenq commented on packages/notification/server/helpers/index.js
> +    ...data
...data сверху укажи, раз говоришь не переопределять app_id

2021-04-08 16:17 UTC, lupenq commented on styleguide/package.json
> +    "react-native-onesignal": "^4.0.5",
Оно ведь в депенденсах @startupjs/notification стоит

2021-04-08 16:18 UTC, lupenq commented on yarn.lock
> +react-native-webview@10.10.2, react-native-webview@^10.0.0:
смержи мастер, пропадет эта строчка

2021-04-13 07:09 UTC, pturchik requested changes

2021-04-13 07:09 UTC, pturchik commented on packages/notification/server/initDefaultRoutes.js
> +    const { ...data } = req.body
а зачем ты их копируешь ? ты их потом собираешься модифицировать ?

2021-04-13 07:09 UTC, pturchik commented on packages/notification/server/initDefaultRoutes.js
> +      sendNotification(data)
await ?

2021-04-13 07:09 UTC, pturchik commented on packages/notification/server/initDefaultRoutes.js
> +    res.status(200).send('ok')
res.status(200).end()

2021-04-13 07:09 UTC, pturchik commented on packages/notification/server/initDefaultRoutes.js
> +      res.status(400).send('No ONESIGNAL_APP_ID')
res.status(400).send(new Error('APP_ID is missing') ?

2021-04-13 07:09 UTC, pturchik commented on packages/notification/server/initNotifications.js
> +  ee.on('afterSession', expressApp => {
давай сделаем проще

```js
import routes from './routes'

ee.on('afterSession', routes)
```

```js
// routes.js

expressApp.use('/api/notifications', api) // api это твои роуты /send, ...
```

плюс тебе точно нужно это делать в `afterSession` ? может в `ee.on('routes')`? я вот ща думаю что может тогда и пакет назвать как-то ещё `pushNotificatons` потому что у нас в dmapper'е есть `notifications` уже и вполне там будут роуты `/api/notifications`?

2021-04-13 07:11 UTC, pturchik requested changes

2021-04-13 07:11 UTC, pturchik commented on packages/notification/docs/notification.ru.mdx
> +  `react-native-onesignal>=4.0.5`
тебе не нужны отступы в заголовках

2021-04-13 07:11 UTC, pturchik commented on packages/notification/docs/notification.ru.mdx
> +  `react-native-onesignal>=4.0.5`
поправь везде

2021-04-13 07:30 UTC, ssstelsss commented on styleguide/server/index.js
> +import { initNotifications, getHeaderOneSignal } from '@startupjs/notification/server'
переименовал в push-notifications

2021-04-13 07:38 UTC, pturchik requested changes

2021-04-13 07:38 UTC, pturchik commented on packages/notification/docs/notification.ru.mdx
> +    ${getHeaderOneSignal()}
getOneSignalHead

2021-04-13 07:38 UTC, pturchik commented on packages/notification/server/getHeaderOneSignal.js
> +<script>
@cray0000 мы хотим чтобы пользователи регистрировались в one-signal до момента авторизации? если нет то нам нужно этот скрипт вынести в какой-то компонент который для веба вернет верстку после того как пользователь авторизирован + setExternalUserId мы сможем делать прям внутри библиотеки завязываясь на userId. что думаешь?

2021-04-13 07:46 UTC, ssstelsss commented on styleguide/config.json
> +  "ONESIGNAL_APP_ID": "6829ff30-f7ac-4a04-9c41-35274fa62fc7"
да, тестовые

2021-04-13 08:49 UTC, ssstelsss commented on styleguide/public/OneSignalSDKUpdaterWorker.js
> +importScripts('https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js')
в доке oneSignal указано, что его нужно добавить

2021-04-27 10:34 UTC, closed without merging