fix(auth): local forms
startupjs/startupjs pull request #606
Opened 2021-04-07 08:56 UTC by lilhakk

2021-04-07 09:25 UTC, lupenq commented on styleguide/auth/index.styl
> +  padding-top 8
А почему не unit?

2021-04-07 12:36 UTC, lupenq approved these changes

2021-04-08 11:30 UTC, pturchik commented
ПР надо сделать в ветку next и написать что теперь auth библиотека не требует async-storage, restart библиотеки

2021-04-08 11:36 UTC, pturchik requested changes

2021-04-08 11:36 UTC, pturchik commented on packages/auth/readme.md
> +    // req.cookies.authRedirectUrl = '/custom-redirect-path'
мне не нравится что людям нужно знать о том что в куку надо поставить authRedirectUrl. может быть нужно кидать в next redirectUrl или как-то ещё, так как это внутреняя логика библиотеки то что мы в куках держим

2021-04-08 16:21 UTC, lilhakk commented on packages/auth/readme.md
> +    // req.cookies.authRedirectUrl = '/custom-redirect-path'
Так линейная логика же получается, и на клиенте можно сетить куку с неймом authRedirectUrl, и на сервере. Или лучше это все скрыть, дабы не было хаков различных в дальнейшем?

По поводу async-storage и restart - там новую логику же уже в мастер закинули с редиректами

2021-04-09 13:12 UTC, pturchik commented on packages/auth/readme.md
> +    // req.cookies.authRedirectUrl = '/custom-redirect-path'
так если новую логику закинули почему пакеты эти там не выпилили? люди же в проекте у себя их оставят не зная о том что они больше не нужны авторизации.

хотелось бы как-то это скрыть, люди на проекте должны помнить о том что в куку, о том что в authRedirectUrl поле именно положить надо. им проще будет если у тебя будет какой-то способ его просто передать куда-то а оно само там сделает как надо

2021-04-09 13:12 UTC, pturchik commented on packages/auth/readme.md
> +    // req.cookies.authRedirectUrl = '/custom-redirect-path'
а как они на клиенте могут засетить можешь пример привести?

2021-04-12 09:19 UTC, lilhakk commented on packages/auth/readme.md
> +    // req.cookies.authRedirectUrl = '/custom-redirect-path'
Через CookieManager.set - я добавил функцию в auth/helpers

2021-04-12 21:32 UTC, merged