fix(Autosuggest): fix search with non-letter characters
startupjs/startupjs pull request #617
Opened 2021-04-14 13:39 UTC by olvipi

2021-04-14 15:39 UTC, pturchik requested changes

2021-04-14 15:39 UTC, pturchik commented on packages/ui/components/AutoSuggest/index.js
> +        ? inputValue.replace(reRegExpChar, '\\$&')
а зачем каждый раз в фильтре реплейсить regexp если можно пойти одной логикой, всегда пытаться реплейсить inputValue

2021-04-14 16:50 UTC, olvipi commented on packages/ui/components/AutoSuggest/index.js
> +        ? inputValue.replace(reRegExpChar, '\\$&')
так реплейсим только если в inputValue есть символы которые необходимо экранировать, если их нет возвращаем inputValue и его тестим

2021-04-15 12:40 UTC, lilhakk approved these changes

2021-04-15 13:25 UTC, merged