feat(app): alert, confirm, prompt
startupjs/startupjs pull request #621
Opened 2021-04-15 12:38 UTC by lilhakk

2021-04-20 10:04 UTC, pturchik requested changes

2021-04-20 20:38 UTC, lilhakk commented on packages/app/client/helpers/popups.js
> +    actions: actions || {}
думаю нет, сами функции уже передают в _page.app.dialog только определенные пропсы, доп. валидации какой-то пока не требуется

2021-04-21 07:32 UTC, pturchik requested changes

2021-04-21 07:32 UTC, pturchik commented on packages/app/client/helpers/dialogs.js
> +const dialogClose = () => $dialog.del()
наверное close даже можно убрать, модалка же вроде сама закроет себя на любой из экшенов если я правильно помню

2021-04-21 07:32 UTC, pturchik commented on packages/ui/components/Modal/layout.js
> +    onCancel: (onCancel !== null) && _onCancel,
можем мы вообще все обработчики так сделаем а то у нас сейчас как я понимаю кнопки всегда все показываются?

```js
let _onConfirm
let _onCancel
let _onCrossPres
let _onBackdropPress

if (onConfirm) {
  _onConfirm = ...
}

if (onCancel) {
  _onCancel = ...
}


```

2021-04-21 07:32 UTC, pturchik commented on packages/ui/components/Modal/layout.js
> +    onCancel: (onCancel !== null) && _onCancel,
что думаешь? это можно тогда в отдельную таску выделить будет

2021-04-21 08:57 UTC, pturchik requested changes

2021-04-21 08:57 UTC, pturchik commented on packages/app/client/helpers/path.js
> +  return `${APP_PATH}.${path}`
только тут если path'а не будет то путь будет `APP_PATH.` - наверное надо полноценный иф сделать

2021-04-21 09:00 UTC, pturchik requested changes

2021-04-21 09:00 UTC, pturchik commented on packages/app/client/helpers/path.js
> +  return `${APP_PATH}.${path}`
```js
funciton generatePath (subpath) {
  let path = '_page.app'
  if (subpath && typeof subpath === 'string) path += `.${subpath}`
  return path
```

2021-04-26 07:38 UTC, pturchik commented
нужно ещё добавить документацию как этим пользоваться, в раздел `General` давай пока запихнем к примеру `Interaction: alert, prompt, confirm`

2021-04-26 07:38 UTC, pturchik requested changes

2021-04-26 07:38 UTC, pturchik commented on packages/app/client/helpers/path.js
> +    if (typeof path !== 'string') {
`typeof subpath !== 'string'`

2021-04-26 07:38 UTC, pturchik commented on packages/app/client/helpers/dialogs.js
> +        Span(style={ marginBottom: 8 })= message
мы обычно использует марджины лево верх, может проще `Br(half)` или перенести margin в `PromptInput`

2021-04-26 07:38 UTC, pturchik commented on packages/app/client/helpers/dialogs.js
> +    onConfirm: dialogClose
наверное лучше кинуть пустую функцию и написать коммент о том что **модалка сама закрывает на экшены себя, возможно нам стоит поменять это поведение в будущем**, а то сейчас получается два раза будет удаление (1 раз твой onConfirm второй раз модалка лупанет)

2021-04-26 07:38 UTC, pturchik commented on packages/app/client/components/Dialog/index.js
> +      showCross=false
стоит ли отключить `enableBackdropPress` ? иначе не понятно какой экшен будет срабатывать. либо тогда уже прокинуть в него соответствующие функции для каждого из типов, считать его за cancel.

2021-04-26 07:38 UTC, pturchik commented on packages/app/client/components/Dialog/index.js
> +    )= dialog.content
кстати ты можешь убрать `= dialog.content` и просто в своих методах кидать в `children` вместо `content`.

```js
dialogOpen({ title, children: message, ... })
```

2021-04-29 08:59 UTC, closed without merging