feat(2fa-manager): add 2fa-manager package
startupjs/startupjs pull request #624
Opened 2021-04-19 08:55 UTC by ssstelsss

2021-04-21 12:02 UTC, lupenq approved these changes

2021-05-13 12:59 UTC, pturchik requested changes

2021-05-13 12:59 UTC, pturchik commented on packages/2fa-totp-authentication/isomorphic/constants.js
> +export const CREATE_SECRET_URL = '/2fa-totp-authentication/create-secret'
/api/2fa-totp-...

2021-05-13 13:05 UTC, pturchik requested changes

2021-05-13 13:05 UTC, pturchik commented on styleguide/server/index.js
> +    providers: [{
```js
providers: [
  [TotpProvider, options],
  ...
]
```

2021-05-13 13:11 UTC, pturchik requested changes

2021-05-13 13:11 UTC, pturchik commented on packages/2fa-manager/README.md
> +  initTwoFAManager(ee, {
spaces

2021-05-13 13:11 UTC, pturchik commented on packages/2fa-manager/client/helpers/getProviders.js
> +    const { data } = await axios.get(GET_PROVIDERS_URL)
?

2021-05-13 13:11 UTC, pturchik commented on packages/2fa-manager/docs/2fa-manager.en.mdx
> +  initTwoFAManager(ee, {
spaces

2021-05-13 13:11 UTC, pturchik commented on packages/2fa-manager/docs/2fa-manager.en.mdx
> +## Example
**Example**

2021-05-13 13:11 UTC, pturchik commented on packages/2fa-manager/docs/2fa-manager.en.mdx
> +### initTwoFaManager(ee, options)
?

2021-05-14 07:55 UTC, merged