feat(recaptcha): add enterprise recaptcha
startupjs/startupjs pull request #630
Opened 2021-04-21 10:44 UTC by lupenq

2021-04-21 11:13 UTC, ssstelsss commented on packages/recaptcha/server/index.js
> +      $session.setEach('Recaptcha', options)
может лучше сделать поле _recapcha, чтобы было понятно, что поле приватное

2021-04-21 11:50 UTC, ssstelsss approved these changes

2021-05-05 08:23 UTC, pturchik requested changes

2021-05-05 08:23 UTC, pturchik commented on packages/recaptcha/server/index.js
> +      $session.setEach('Recaptcha', options)
```js
function initRecaptcha (ee, options) {
  options = defaults(options, { type: 'enterprise' }) - или какой там тип будет дефолтный
  ee.on('afterSession', expressApp => {
    expressApp.use(setRecaptchaSiteKey(options))
  })
}
```

2021-05-05 08:23 UTC, pturchik commented on packages/recaptcha/server/middlewares/setRecaptchaSiteKey.js
```js
export default function setRecaptcha (options) {
  ... тут и сеть что нужно в сессию
  return (req, res, next) => {
    switch (options.type) {
      case 'enterprise':
         ...
         break
      ...
    }
  }
}
```

2021-05-05 08:23 UTC, pturchik commented on packages/recaptcha/server/helpers/checkEnterpriseToken.js
> +  const ENTERPRISE_INVISIBLE_SITE_KEY = nconf.get('RECAPTCHA_ENTERPRISE_INVISIBLE_SITE_KEY')
тебе нужно отдать из пакета всего лишь одну функцию `checkRecaptcha` и в ней уже самому разруливать по типу как и что проверить, для enterprise захардкодить пока значение в 0.3, 0.5 - какое там рекомендуют использовать

2021-05-05 08:23 UTC, pturchik commented on packages/recaptcha/server/checkToken.js
> +export default async function checkToken (options) {
```js
export default async function checkRecaptcha (params) {
  switch (params.type) {
    case 'enterprise':
       await checkEnterprise()
       break
     ...
  }
}
```

2021-05-05 08:23 UTC, pturchik commented on packages/recaptcha/readme/readme.en.mdx
> +Using reCAPTCHA Enterprise on the client differs from using reCAPTCHA v2 only in that the callback `onVerify` of the `Recaptcha` component returns an object `{token: 'token', variant: 'normal of visi
им не обязательно вообще знать что там происхоидт, твой onVerify должен выглядеть так
```js
function onVerify (recaptcha) {
  await axios.post(url, { recaptcha, ... })
}
```
+ поправь пример в доке как использовать капчу

2021-05-05 08:23 UTC, pturchik commented on styleguide/server/initRecaptchaDoc.js
> +    const isVerified = await checkToken({ token, type, variant })
тут тебе должен просто прилетать `req.body.recaptcha` который они дальше должны передать в `checkRecaptcha(recaptcha)`

2021-05-06 15:40 UTC, closed without merging