ref(mdx): redafctor jsx example
startupjs/startupjs pull request #652
Opened 2021-05-06 15:21 UTC by lupenq

![image](https://user-images.githubusercontent.com/25533519/117323656-c3034c00-ae97-11eb-8770-70f3d1789029.png)

![image](https://user-images.githubusercontent.com/25533519/117323700-cbf41d80-ae97-11eb-89a3-44184654c8a8.png)

2021-05-12 12:37 UTC, ssstelsss approved these changes

2021-05-19 13:40 UTC, pturchik requested changes

2021-05-19 13:40 UTC, pturchik commented on packages/mdx/client/mdxComponents/index.js
> +        setTimeout(() => setCopyText(' Copy code '), 3000)
может удалить на onMouseLeave? просто делать setDiff('Copy code')?

2021-05-19 13:40 UTC, pturchik commented on packages/mdx/client/mdxComponents/index.styl
> +  padding 0 2u 2u
padding 2u

2021-05-19 13:40 UTC, pturchik commented on packages/mdx/client/mdxComponents/index.styl
> +  padding 0 2u 2u
padding 2u

2021-05-19 13:40 UTC, pturchik commented on packages/mdx/client/mdxComponents/index.styl
> +  opacity .5
зачем нужен этот opacity ? цвет иконок серый, при ховере темнее и все прекрасно выглядит.

2021-05-19 15:03 UTC, lupenq commented on packages/mdx/client/mdxComponents/index.styl
> +  opacity .5
опасити тут нужен. так она серенькая, при ховере темнеет. Если убрать, то она будет черная, а при ховере совсем немного светлеть

2021-05-19 15:08 UTC, lupenq commented on packages/mdx/client/mdxComponents/index.js
> +        setTimeout(() => setCopyText(' Copy code '), 3000)
onMouseLeave мне не нравится, он отработает быстрее, чем пропадет тултип, из-за этого ты увидишь надпись Copy code

2021-05-19 15:27 UTC, pturchik commented on packages/mdx/client/mdxComponents/index.js
> +        setTimeout(() => setCopyText(' Copy code '), 3000)
так а ты сделай `setTimeout(() => setDiff(...), 0)`

2021-05-19 15:33 UTC, pturchik commented on packages/mdx/client/mdxComponents/index.styl
> +  opacity .5
так ты поставь цвет иконки правильны и тогда при ховере она будет опасититься так как заложено у дива или если дашь variant='higlight' то будет подсвечиваться бэкграунд

2021-05-19 21:18 UTC, pturchik requested changes

2021-05-19 21:18 UTC, pturchik commented on packages/bundler/lib/mdxExamplesLoader.js
> +  const code = `\n\n${p1}${p2}${p3}\n`
в конце `\n` можно тогда убрать

2021-05-19 21:24 UTC, olvipi commented on packages/mdx/client/mdxComponents/index.js
> +        setTimeout(() => setCopyText(' Copy code '), 3000)
[clipboard](https://github.com/react-native-clipboard/clipboard)

2021-05-21 13:12 UTC, pturchik requested changes

2021-05-21 13:12 UTC, pturchik commented on packages/mdx/client/mdxComponents/index.js
> +      Div.code
br-ка то должна быть и у блока `if example` поэтому проще дать марджин `.code`

2021-05-21 13:12 UTC, pturchik commented on packages/mdx/client/mdxComponents/index.js
> +                    onMouseLeave=() => setTimeout(() => $copyText.setDiff('Copy code'), 300)
теоритечиски ты можешь успеть навестись снова за 300 мс? тогда надо на `onMouseEnter` делать `clearnTimeout` и таймер записывать в `ref`

2021-05-21 13:12 UTC, pturchik commented on packages/mdx/client/mdxComponents/index.styl
> +.code-action
`.code-action` идет первее в верстке, так и пиши в стилях его первее)

2021-05-24 08:41 UTC, merged