F sstelss pus notifications firebase
startupjs/startupjs pull request #656
Opened 2021-05-07 15:26 UTC by ssstelsss

2021-05-11 09:54 UTC, pturchik requested changes

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/server/initFirebaseApp.js
> +  console.log('JSON.parse(serviceAccount): ', JSON.parse(serviceAccount))
remove

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/isomorphic/constants.js
> +export const SEND_URL = '/push-notifications/send'
'/api/...'

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/package.json
> +    "react-native-push-notification": ">= 7.2.3"
в алфавитном порядке

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/server/initDefaultRoutes.js
> +  router.get(GET_USERS_URL, async function (req, res) {
remove

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/server/initPushNotifications.js
> +  ee.on('afterSession', expressApp => {
ee.on('routes', ...)

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/server/helpers/sendNotification.js
> +  const platforms = getPlatforms(data.filters)
if (!data.userIds) {
  console.error('...')
  return
}

если можно отправить только body то валидируем на него, если нужно все то валидируем и title и body.

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/server/helpers/sendNotification.js
> +  if (filters.platforms?.length) {
fitlers?.

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/README.md
> +
?

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/client/helpers/initAndroidChannel.js
> +export default function initAndroidChannel (options, callback = defaultCallback) {
can we remove defaultCallback?

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/client/helpers/registerDevice.js
> +  const $pushAcc = $root.scope(`pushs.${userId}`)
$push

2021-05-11 09:54 UTC, pturchik commented on packages/push-notifications/client/helpers/registerDevice.js
> +    $pushAcc.set(`platforms.${token.os}`, token.token)
setDiff

2021-05-11 10:02 UTC, pturchik requested changes

2021-05-11 10:02 UTC, pturchik commented on packages/push-notifications/client/helpers/sendNotification.js
> +export default async function sendNotification (userIds, title, body, androidChannelId, filters = {}) {
`sendNotifications(userIds, options)`, where options:
- `title [String] (optional)` ......
- `body [String = 'default value' ] (required)` ...
- any other [firebase](...) options

2021-05-26 10:17 UTC, pturchik requested changes

2021-05-26 10:17 UTC, pturchik commented on packages/push-notifications/client/components/Messages/index.js
> +              Span Created At
`Span` можно не писать `Th` сама их вставит

2021-05-26 10:17 UTC, pturchik commented on packages/push-notifications/client/components/Messages/index.js
> +        if pushMessages.length
не нужно ставить эти ифы, пусть будет пустой tbody если массив нулевой длины

2021-05-26 10:17 UTC, pturchik commented on packages/push-notifications/client/components/Messages/index.js
> +                  Span= _get(pushMessage, 'options.filters.platforms', ['ios', 'android']).join(', ')
в документе `message` лежит `options.filters.platforms`? может нам просто как-то это все инлайн ложить

pushMessageDoc
{ platforms: [..], userId: ..., body, .... }

2021-05-26 10:17 UTC, pturchik commented on packages/push-notifications/client/components/Messages/index.js
> +    unless pushMessagesCount <= LIMIT
пусть пагинация показывается всегда

2021-05-26 10:17 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/DeliveryConfigBlog/index.js
> +        Div.androidChannelBlock
remove this block

2021-05-26 10:17 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/DeliveryConfigBlog/index.js
> +        Checkbox.checkboxAllUsers(
remove all users checkbox

2021-05-26 10:17 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/DeliveryConfigBlog/index.js
> +          )
тебе по идеи этот текст инпут тоже не нужен если если мы удалим `all users checkbox`. у тебя же отправляется конкретному юзеру? может тогда сделать какую-то форму для отправки многим?

2021-05-26 10:17 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/DeliveryConfigBlog/index.styl
> +  margin-top 2u
по идеи все эти марджины ты мог разметить br'ами или написать

```styl
.class1
.class2
.class3
  margin-top 2u
```

2021-05-26 12:38 UTC, pturchik requested changes

2021-05-26 12:38 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/MessageBlock/index.js
> +                Span.appName app name
app name ?

2021-05-26 12:38 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/MessageBlock/index.styl
> +  z-index 100
z-index здесь зачем?

2021-05-26 12:38 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/index.js
> +  userId: PropTypes.string,
userIds

2021-05-26 12:38 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/index.js
> +    sendNotification(recipientIds, { ...options })
`sendNotification(userIds, data)`
userIds - залетают в компонент
data из useValue, тебе не нужен дефолт никакой где тупо пустые строчки,

2021-05-27 14:58 UTC, ssstelsss commented
![image](https://user-images.githubusercontent.com/58818714/119849066-fbd19680-bf14-11eb-8ab0-0a6968ae4682.png)
![image](https://user-images.githubusercontent.com/58818714/119849109-03913b00-bf15-11eb-88b9-5f5e8c5cacfe.png)
![image](https://user-images.githubusercontent.com/58818714/119849163-11df5700-bf15-11eb-822a-74c5aa4acda1.png)

2021-05-31 08:21 UTC, pturchik requested changes

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/client/components/Messages/index.js
> +  const [pushMessagesCount = 0] = useQuery('pushMessages', { $count: true })
`$count` возвращает всегда число, нет нужды в значение по умолчанию `= 0`

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/client/components/Messages/index.js
> +              Td= pushMessage.options.body
может мы не будем складывать данные в документе в том виде в котором они летят в функцию, а положим их плоско

то как должен выглядеть документ `pushMessage`

```js
{ title, body, userId, platforms }
```

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/client/components/Accounts/index.js
> +  const [pushsCount = 0] = useQuery('pushs', { $count: true })
`$count` всегда возвращает число, тебе не нужно никакое значение по умолчанию ввиде 0

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/client/components/Accounts/index.js
> +  const [users] = useQuery('users', { _id: { $in: pushs.map(push => push.id) } })
подскажи пожалуйста в нём у нас необходимость того что идентификаторы пуша совпадают с идентификаторами пользователя? мы можем просто хранить в пуше поле userId, и этого должно быть достаточно

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/DeliveryConfigBlog/index.styl
> +.androidChannelBlock
не используется `androidChannelBlock`, `input `, `usersBlock`, `checkboxAllUsers`

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/DeliveryConfigBlog/index.styl
> +.root
компонент не должен иметь никаких отсутпов у главного элемента, такие отступы должны задаваться там где он используется

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/index.js
> +    platforms: []
зачем нужны эти дефолты? зачем вложенность в виде `filters`?

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/server/helpers/sendNotification.js
> +  if (!data.userIds) {
что насчет этого комментария?

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/server/helpers/sendNotification.js
> +  await fadmin.messaging().sendToDevice(
что насчет этого комментария?

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/server/helpers/sendNotification.js
> +    _data.options.title = ''
зачем пустые эти пустые строчки добавляются?

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/server/helpers/sendNotification.js
> +  saveMessage(model, _data, tokens)
await ?

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/server/helpers/sendNotification.js
> +function saveMessage (model, data) {
async?

2021-05-31 08:21 UTC, pturchik commented on packages/push-notifications/server/helpers/sendNotification.js
> +  $pushMessages.add({
await ?

2021-05-31 09:00 UTC, pturchik requested changes

2021-05-31 14:27 UTC, ssstelsss commented on packages/push-notifications/client/components/SendMessageForm/index.js
> +    platforms: []
дефолты, чтобы после отправки сбросить состояния к изначальному значению

2021-05-31 15:12 UTC, ssstelsss commented
![image](https://user-images.githubusercontent.com/58818714/120213301-b1fdee80-c23b-11eb-8269-df27b9b80740.png)
![image](https://user-images.githubusercontent.com/58818714/120213329-baeec000-c23b-11eb-95d5-c0c320def49f.png)

2021-06-01 08:31 UTC, pturchik requested changes

2021-06-01 08:31 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/DeliveryConfigBlog/index.js
> +    }
тут есть проблема в том что если я включу и выключу чекбокс, то там останется пустой массив и в итоге не полетит никуда. возможно будет правильнее сделать чтобы никакие дефолты при отправке не ставить, а тут обязательно нужно включить какую-то из платформ

2021-06-01 08:31 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/MessageBlock/index.styl
> +  padding-top 1u
этот паддинг будет отступом компоненты, лучше задавать его сверху где используешь

2021-06-01 08:31 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/MessageBlock/index.styl
> +  line-height 2.5u
что за кастомный `line-height`?

2021-06-01 08:31 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/MessageBlock/index.styl
> +  line-height 2u
что за кастомный `line-height`?

2021-06-01 08:31 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/MessageBlock/index.styl
> +  width 84%
84%? выглядит как подгонка

2021-06-01 08:31 UTC, pturchik commented on packages/push-notifications/client/components/SendMessageForm/MessageBlock/index.styl
> +  display none
а для расрешения меньше десктопа как посмотреть превью?

2021-06-02 07:42 UTC, pturchik requested changes

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/server/helpers/sendPush.js
> +export default async function sendNotification (model, userIds, options) {
options = {}

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/server/helpers/sendPush.js
> +    console.error('[@startupjs/push-notifications/sendNotification]: userIds is required!')
throw new Error?

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/server/helpers/sendPush.js
> +    console.error('[@startupjs/push-notifications/sendNotification]: body is required!')
throw new Error?

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/server/helpers/sendPush.js
> +  if (!tokens.length) return
может быть если нет токенов то и сохранять не нужно сообщение в pushs?

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/README.md
> +Select `Certificates, Identifiers & Profiles` and go to `Keys`. Click the + circle button to create a new key.
надо бы сказать где, что в апп стор коннект или как там называется эта страничка выберите `Certificates, ...`

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/README.md
> +Go into your MyReactProject/ios dir and open MyProject.xcworkspace workspace. Select the top project "MyProject" and select the "Signing & Capabilities" tab. Add a 2 new Capabilities using "+" button
ты бы повыделял названия папок в ``

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/README.md
> +Go into your MyReactProject/ios dir and open MyProject.xcworkspace workspace. Select the top project "MyProject" and select the "Signing & Capabilities" tab. Add a 2 new Capabilities using "+" button
+ сказал бы где это надо делать - в xcode

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/README.md
> +### Connection
пустая секция?

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/README.md
> +### Connection
наверное правильнее назвать раздел не `Using` а `Connection` или `Connecting the package to your project`

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/README.md
> +- `sendNotification(userIds, options)` - function for sending notifications. - `options [Object]`:
я думаю тебе не нужно раписывать все эти функции подключения, тебе нужно тут добавить раздел `Usage` и показать `sendNotification`

```md
## Usage

### `sendNotification(userIds, options)`
Send notification to users ...

**Arguments**
 ...
**Returns**
...
**Example**
```

посмотри как в других пакетах доку пишем

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/docs/push-notifications.en.mdx
> +      placeholder='title'
смотри комменты к README.md

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/docs/push-notifications.en.mdx
> +      placeholder='title'
тебе достаточно будет показать это как-то попроше
к примеру

```js
function subscribe (planId, userId) {
  const plan = getPlan(planId)
  // plan subscription logic
  sendNotification([userId], { title: 'Subscription ', body: `You have subscribed to plan `${plan.name}` })
}
```

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/server/helpers/sendPush.js
> +      data: data || {}
data is required?

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/README.md
> +![alpha](/img/docs/push-notifications/pushs3.png "Apple Push Notifications service (APNs)")
?

2021-06-02 07:42 UTC, pturchik commented on packages/push-notifications/server/helpers/sendPush.js
> +    if (!_options[key]) {
пустой массив для platforms тоже перезаписывай дефолтом

2021-06-02 07:53 UTC, pturchik commented
options remove, add send notificatoin button to top of the table

2021-06-02 19:23 UTC, merged