fix(ui/Tooltip): new api
startupjs/startupjs pull request #657
Opened 2021-05-11 08:40 UTC by lilhakk

2021-05-12 16:56 UTC, lupenq reviewed
![image](https://user-images.githubusercontent.com/25533519/118014630-170ca580-b35c-11eb-92b1-3ea307cd7e09.png)

2021-05-12 16:56 UTC, lupenq commented on packages/ui/components/Div/Div.ru.mdx
> +## renderTooltip
Добавь и в en доку

2021-05-17 09:15 UTC, lupenq commented
на вебе
![image](https://user-images.githubusercontent.com/25533519/118464517-9fe36280-b709-11eb-87b0-4804a783c719.png)

2021-05-17 09:20 UTC, lupenq commented on packages/ui/components/Div/Div.en.mdx
> +## renderTooltip
Sandbox в самом низу укажи

2021-05-17 09:21 UTC, lupenq commented
На ios просто нажал на компонент с доке (на черный квадрат у которого есть тултип)

![image](https://user-images.githubusercontent.com/25533519/118465178-4f203980-b70a-11eb-8970-34db3a84b535.png)

2021-05-18 08:23 UTC, pturchik requested changes

2021-05-18 08:23 UTC, pturchik commented on packages/ui/components/popups/Popover/usePopover.js
> +  durationOpen = 300,
может `open = 200`, `close = 100`? для таких элементов 300, 200 очень большая задержка, закрытие даже 50 часто ставят

2021-05-18 08:23 UTC, pturchik commented on packages/ui/components/Div/index.js
> +    arrowStyle: showTooltipInvolved ? {} : { color: '#222222' },
а смысл скипать стили пусть всегда летят просто стрелка не всегда показывается. плюс ты можешь их объявить в стилях и экспортнуть из `.styl` их в сюда в `js` файл и подставить в `arrowStyle`

2021-05-18 08:23 UTC, pturchik commented on packages/ui/components/Div/index.js
> +  const [isShowTooltip, setIsShowTooltip] = useState(false)
```js
const [isShowTooltip, setIsShowTooltip] = useState(isTooltipControllable ? _showTooltip : false)

if (isTooltipControllable) {
  useDidUpdate(() => {
    setIsShowtooltip(_showTooltip)
  }, [_showTooltip])
}
```

2021-05-26 07:00 UTC, lilhakk commented on packages/ui/components/Div/index.js
> +  const refCaption = useRef()
Я пробывал сделать, пока были траблы в AutoSuggest, когда ref вне компонента объявляется. Возможно потому что refCaption в хук передается и что-то не обновляется в итоге.

2021-05-26 07:01 UTC, lilhakk commented on packages/ui/components/Div/index.js
> +  } = usePopover({
Думаю можно так сделать, usePopover щас в Div используется только

2021-05-26 07:02 UTC, lilhakk commented on packages/ui/components/popups/Popover/usePopover.js
> +  refCaption = null,
Ну типа, если ref не передан и он null, то работать не будет ничего. Хз как сделать required параметр через хук

2021-05-26 07:05 UTC, lilhakk commented on packages/ui/components/Tooltip/useTooltip.web.js
> +    }, 200)
Иначе Portal начинает тупить, бывает такая логика что тултипов сразу по 100 штук в ряд обрабатывается, и тупо не успевает все перерендериваться нормально

2021-05-27 16:53 UTC, closed without merging