feat(ui/Toasts): add
startupjs/startupjs pull request #687
Opened 2021-06-01 08:11 UTC by lilhakk

2021-06-22 19:43 UTC, pturchik requested changes

2021-06-22 19:43 UTC, pturchik commented on packages/ui/components/Toast/index.js
> +export { default as toast } from './toast'
надо добавить в `createModuleMap` чтобы оно добавило оба этих файла

2021-07-23 07:43 UTC, pturchik requested changes

2021-07-23 08:55 UTC, pturchik requested changes

2021-07-23 08:55 UTC, pturchik commented on packages/ui/helpers/uiAppPlugin.js
> +          ToastProvider= children
нам нужно чтобы тоасты были всегда выше любого другого окна, даже модалки. может как-то их в отдельный контекст или порешать это z-index'ом можно?

2021-07-23 08:55 UTC, pturchik commented on packages/ui/components/Toast/ToastComponent.js
> +      Animated.View.alert(
почему класс alert? ведь они могут быть и банеры и алерты?

2021-07-23 08:55 UTC, pturchik commented on packages/ui/components/Toast/index.styl
> +  margin-bottom 1u
отступа быть не должно, они должны анимироваться на нужную позицию иначе анимация будет идти до позиции а потом применяться марджин же.

плюс надо сделать для мобильного разрешения свои стили (снизу на темненьком фоне, посмотри как было раньше) поэтому скорее всего тебе alert может и не выгодно использовать и нужно будет заверстать и десктоп и мобилку

2021-07-23 08:55 UTC, pturchik commented on packages/ui/components/Toast/ToastComponent.js
> +      Animated.timing(animateStates.height, { toValue: 0, duration: 300 })
зачем высоту анимировать? просто анимируем opacity + позицию из-за экрана

2021-07-23 08:55 UTC, pturchik commented on packages/ui/components/Toast/ToastComponent.js
> +      Animated.timing(animateStates.height, { toValue: 0, duration: 300 })
причем было бы не плохо иметь Toast компонент который по сути чисто верстка мобильная или не мобильная. а над ним уже animted view который опаситит и выдвигает из-за экрана. причем анимация должна быть ещё на сдвиг при добавлении нового.

2021-07-23 08:55 UTC, pturchik commented on packages/ui/components/Toast/callToast.js
> +    content,
1. тоасты должны жить над всем приложением а не только на странице конкретной, чтобы при переходе по страницам они оставались висеть. используй контекст должно быть норм.
2. не нужно подгонять апи тостов под апи `Alert` компоненты. если ты и хочешь использовать `Alert` внутри тоастов то передавай как тебе нужно а не подгоняй. 
апи тоаста - { title, text, icon, alert, onClose, onAction }, причем если есть onAction добавлять кнопку view, actionLabel можно ещё передавать будет чтобы поменять текст view к примеру.
3. не больше 3 тостов нужно показывать, и менеджить это здесь чтобы не мешать поведение с твоей вьюхой, меняй какой-то `open` состояния в тоасте просто а в onClose удаляй из контекста. а onClose там вызовется когда анимация закрытия закончится.

2021-07-24 11:00 UTC, lilhakk commented on packages/ui/components/Toast/ToastComponent.js
> +      Animated.timing(animateStates.height, { toValue: 0, duration: 300 })
Если не анимировать высоту блоки, под анимированным блоком, просто "зависают", а сверху образуется эффект пустоты, а так все плавно пропадает. Это анимация именно для скрытия блока

2021-07-30 09:55 UTC, lilhakk commented on packages/ui/components/Toast/ToastComponent.js
> +      toValue: getTopPosition((_toastsLength - 1) - _index),
"(_toastsLength - 1) - _index"
Нужно для того чтобы массив элементов рендерился как обычно - [0,1,2,3...], но анимация отрабатывала в обратную сторону - [...3,2,1,0]. Т.е. изначально появляется первый элемент (выезжая справа), затем второй на месте первого (так же выезжая справа), а первый узжает вниз и так далее. И позиция первого будет всегда считаться как позиция последнего

2021-08-02 08:04 UTC, pturchik requested changes

2021-08-02 08:04 UTC, pturchik commented on packages/ui/components/Toast/ToastComponent.js
> +          if onAction
onAction должен после себя вызывать onClose. действие приводит к закрытию всегда

2021-08-02 08:04 UTC, pturchik commented on packages/ui/components/Toast/ToastComponent.js
> +    onClose && onClose()
тебе понадобится ещё какой-то onFinishClose который будет вызываться когда закончится анимация закрытия которым ты и будешь удалять из массива элемент

2021-08-02 21:41 UTC, lilhakk commented on packages/ui/components/Toast/ToastComponent.js
> +    Animated.View.animate(style={
<img width="672" alt="Снимок экрана 2021-08-03 в 00 40 42" src="https://user-images.githubusercontent.com/20387883/127927348-c9f7274d-244e-4275-95be-6265589e3b9b.png">

2021-08-02 21:49 UTC, lilhakk commented on packages/ui/components/Toast/ToastComponent.js
> +    Animated.View.animate(style={
<img width="451" alt="Снимок экрана 2021-08-03 в 00 49 11" src="https://user-images.githubusercontent.com/20387883/127928304-7dd63a35-fe88-4300-85e4-66b768cf70d7.png">

2021-08-06 14:13 UTC, pturchik requested changes

2021-08-06 14:13 UTC, pturchik commented on packages/ui/components/toast/toast.js
> +    $toasts.set('2.show', false)
```$toasts.set(`${MAX_SHOW_LENGTH - 1}.show`, false)```

2021-08-06 14:13 UTC, pturchik commented on packages/ui/components/toast/index.styl
> +  width 100%
это для чего? куда и зачем width: 100%?

2021-08-06 14:13 UTC, pturchik commented on packages/ui/components/toast/index.styl
> +  width 100%
аналогично зачем 100%? они и так прекрасно друг друга в себе тянут из-за align-items stretch

2021-08-06 14:13 UTC, pturchik commented on packages/ui/components/toast/ToastComponent.js
> +          Span(numberOfLines=1)= text
хотелось чтобы текст мог быть и в несколько строк. хоть в 100, просто этим не должны пользоваться передвая столько текста так как это выглядит не очень. наверное тогда все таки нужно записывать как-то размер тоаста. к примеру можно с toast.js кидать сюда onLayout и записывать размер. и кидать сюда getPosition функцию которая будет говорить в какой позиции открываться учитывая все размер и марджины. а может просто сразу кидать position и там считать позицию. 

может какие ещё есть варианты как это сделать? подумай пожалуйста. можно конечно в context провайдера писать в onLayout, и как-то потом обсчитывать здесь конкретно в тоасте к примеру. а можно ложить не размеры а сумму всех до тебя, а onLayout будет ложить для следующего сумму с самим собой... в общем подумай как лучше будет чтобы это было максимально просто и понятно

2021-08-07 10:30 UTC, lilhakk commented on packages/ui/components/toast/index.styl
> +  width 100%
для мобилок на всю ширину экрана

2021-08-07 10:32 UTC, lilhakk commented on packages/ui/components/toast/ToastComponent.js
> +          Span(numberOfLines=1)= text
изначально ты говорил что высота будет всегда фиксированной, нужно через getTopPosition сначала отрендерить и посчитать высоту в onLayout, а потом все анимировать как и поповере

2021-08-09 08:13 UTC, pturchik commented on packages/ui/components/toast/index.styl
> +  width 100%
ну так тогда наверное этот блок и должен иметь размеры для мобилки, не для мобилки а внутри него просто все тянуться по нему а не вглубь прописывать width: 100% и где-то там потом вглубине делать для мобилких ограниченную ширину

2021-08-09 08:14 UTC, pturchik commented on packages/ui/components/toast/ToastComponent.js
> +          Span(numberOfLines=1)= text
угум, так было и задумано изначально. сделать простую компоненту которую мы и расширим. вот как раз время пришло )

2021-08-10 11:01 UTC, lilhakk commented on packages/ui/components/toast/ToastComponent.js
> +  info: 'Info',
Я там щас юзаю Info как дефолт, у каждого типа есть свой дефолтный заголовок + иконка

2021-08-10 11:44 UTC, lilhakk commented on packages/ui/components/toast/ToastComponent.js
> +    Animated.parallel([
оно само прерывает onShow анимацию, и начинает выполнять onHide с момента где закончилась onShow

2021-08-12 08:50 UTC, pturchik requested changes

2021-08-20 12:51 UTC, merged