(WIP) feat(2fa-push-notification-provider): add package
startupjs/startupjs pull request #694
Opened 2021-06-03 10:14 UTC by ssstelsss

2021-06-03 12:41 UTC, pturchik requested changes

2021-06-03 12:41 UTC, pturchik commented on styleguide/server/index.js
> +      [PushProvider, {}]
remove {}

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-push-notification-provider/server/Provider.js
> +    const $2fas = model.query('2fa', { userId })
$limit: 1

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-push-notification-provider/server/Provider.js
> +    sendNotification([userId], {
await

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-push-notification-provider/server/Provider.js
> +    })
$2fa.unsubscribe

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-push-notification-provider/server/Provider.js
> +    const $2fas = model.query('2fa', { userId, $limit: 1 })
{ userId, $limit: 1, 'push.code': code, createdAt: { $lte: ... } }

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-push-notification-provider/server/Provider.js
> +    const $2fas = model.query('2fa', { userId, $limit: 1 })
```js
const [twoFa] = $2fas.get()
const isExist = !!twoFa
let result = false
if (isExist) {
  $2fa.del('push.code')
  result = true
}

$2fa.unsubscribe()
return result
```

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-push-notification-provider/server/Provider.js
> +          code: randomCode
createdAt: ..

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-manager/Provider/Provider.js
> -  init (ee, options) {
remove async

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-push-notification-provider/server/Provider.js
> +    this.init(ee, options)
remove

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
> +    send(selectedProvider)
await

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
> +    send(selectedProvider)
if (sended) then setIsSended() else setError()

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
>    const [selectedProvider, setSelectedProvider] = useState('')
remove ''

2021-06-03 12:41 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
> +          Button.sendButton(onPress=() =>setSelectedProvider('')) Back
remove ''

2021-06-04 06:48 UTC, pturchik requested changes

2021-06-04 06:48 UTC, pturchik commented on packages/2fa-push-notification-provider/docs/push-notifications.ru.mdx
> +Компонент провайдера для верификации через `@startupjs/push-notification`.
врядли это прям компонент ) просто "провайдер для ..."

2021-06-04 06:48 UTC, pturchik commented on packages/2fa-push-notification-provider/docs/push-notifications.ru.mdx
> +## !ВАЖНО!
это не совем прям раздел, это примечание больше поэтому семантичнее будет `**ВАЖНО**: ...`

2021-06-04 06:48 UTC, pturchik commented on packages/2fa-push-notification-provider/docs/push-notifications.ru.mdx
> +Затем нужно добавить `PushProvider` в массив `providers` у `initTwoFAManager`. Второй аргумент массива - это опции для провайдера. Здесь можно задать, необязательный параметр `timeWindowMs`, это врем
`timeWindowMs` -> `maxAge` || `codeMaxAge` || `lifeTime` || `codeLifeTime` ...

2021-06-04 06:48 UTC, pturchik commented on packages/2fa-push-notification-provider/docs/push-notifications.en.mdx
> +# @startupjs/2fa-push-notification-provider
скопируй эту доку в `README.md`

2021-06-04 06:48 UTC, pturchik commented on packages/2fa-totp-authentication-provider/README.md
> +import { PushProvider } from '@startupjs/2fa-push-notification-provider'
это дока totp, а тут ты про пуши пишешь

2021-06-04 06:48 UTC, pturchik commented on packages/2fa-push-notification-provider/server/Provider.js
> +    let result = false
по сути `isExist` и есть `result`

```js
const isExist = !!twoFa
if (isExist) await model.scope(`2fa.${twoFa.id}`).del()
$2fas.unsubscribe()
return isExist
```

а если вернется false то человек скажется на клиенте что `code` не верный ... ?

2021-06-04 12:20 UTC, pturchik requested changes

2021-06-04 12:20 UTC, pturchik commented on packages/2fa-totp-authentication-provider/docs/2fa-totp-authentication-provider.en.mdx
>    providers: [GAProvider]
тут забыл поменять

2021-06-04 12:20 UTC, pturchik commented on packages/2fa-totp-authentication-provider/README.md
> +  providers: [GAProvider]
тут забыл поменять

2021-06-04 12:21 UTC, pturchik requested changes

2021-06-04 12:21 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
> +    setCode('')
setCode()

2021-06-04 12:21 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
> +      setTimeout(() => {
зачем через 5 секунд очищать? очищай при следующем сенде

2021-06-04 12:24 UTC, pturchik requested changes

2021-06-04 12:24 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
> +    onSend(provider)
логику onSend надо сюда перенести и
try {
  setSelectedProvider(provider)
} catch () {
  setError(true)
}

2021-06-04 12:24 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
>    const [code, setCode] = useState('')
const [code, setCode] = useState()

2021-06-04 12:31 UTC, pturchik requested changes

2021-06-04 12:31 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
> +    onSubmit({ selectedProvider, code })
Incorrect verification code.

2021-06-04 12:31 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
> +    onSubmit({ selectedProvider, code })
verification_err

2021-06-04 12:31 UTC, pturchik commented on packages/2fa-manager/client/components/ProvidersBlock/index.js
> +        Alert(variant='error') Something went wrong. Try again in 5 minutes
constants[err]

2021-06-04 13:10 UTC, ssstelsss commented
![image](https://user-images.githubusercontent.com/58818714/120806176-352a8780-c54f-11eb-8ef6-117dc511bbae.png)
![image](https://user-images.githubusercontent.com/58818714/120806306-5ee3ae80-c54f-11eb-9c78-500b5813b225.png)

2021-06-07 06:53 UTC, merged