ref(ui/DatePicker): timezone
startupjs/startupjs pull request #701
Opened 2021-06-08 10:04 UTC by lilhakk

2021-06-08 19:59 UTC, olvipi requested changes

2021-06-17 08:17 UTC, olvipi requested changes

2021-06-17 08:17 UTC, olvipi commented on packages/ui/components/forms/DatePicker/index.js
> +    const timeshtamp = moment(textInput, _formatInput)
momentInstance

2021-06-17 08:17 UTC, olvipi commented on packages/ui/components/forms/DatePicker/index.js
> +      onChangeDate(+timeshtamp)
спорный вопрос стоит ли вызывать коллбек при отказе

2021-06-17 08:17 UTC, olvipi commented on packages/ui/components/forms/DatePicker/index.js
> +  is24Hour: true,
тут можно автоматически по локали определить new RegExp(/a/i).test(moment()._locale._longDateFormat.LT)

2021-06-17 08:27 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/index.js
> +      onChangeDate(+timeshtamp)
при отказе?

2021-06-17 08:28 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/index.js
> +  is24Hour: true,
у кого-то юзается онли 12 форматное время?

2021-06-17 08:29 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/index.js
> +    const timeshtamp = moment(textInput, _formatInput)
?

2021-06-17 08:29 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/Calendar/Header/index.js
> +  // faAngleDoubleLeft,
точно эти кнопки не нужны будут?

2021-06-17 08:30 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/Calendar/Header/index.js
> +        // Button(
точно эти кнопки не нужны будут?

2021-06-17 08:32 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/Calendar/index.js
> +    $slide.set('days')
Это же просто изменение стринги, тут можно обойтись вообще useState/setSlide

2021-06-17 08:34 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/Calendar/slides/Days/index.js
> +    const currentDay = moment
А дальше идет currentDay.add(1, 'd'), в контексте currentDay - значит текущий используемый день. firstDay - больше для неизменяемой константы

2021-06-17 08:35 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/Calendar/slides/Years/index.js
> +    const currentYear = moment.tz(uiDate, timezone).startOf('Y').add(-7, 'y')
тоже самое https://github.com/startupjs/startupjs/pull/701#discussion_r653349608

2021-06-17 08:35 UTC, olvipi commented on packages/ui/components/forms/DatePicker/Calendar/Header/index.js
> +  // faAngleDoubleLeft,
надо обсудить

2021-06-17 08:35 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/Calendar/slides/Years/index.js
> +    for line, lineIndex in prepareYears
мб +

2021-06-17 08:36 UTC, olvipi commented on packages/ui/components/forms/DatePicker/Calendar/slides/Days/index.js
> +    const currentDay = moment
или отправной точки

2021-06-17 08:37 UTC, olvipi commented on packages/ui/components/forms/DatePicker/index.js
> +    const timeshtamp = moment(textInput, _formatInput)
timestamp это число, в даном случае ты создаеш инстанс moment

2021-06-17 08:39 UTC, olvipi commented on packages/ui/components/forms/DatePicker/index.js
> +      onChangeDate(+timeshtamp)
кейс, дата уже была, ты открыл пикер и начал что то выбирать но передумал - по идее дата при дисмисе не должна менятся

2021-06-17 08:41 UTC, olvipi commented on packages/ui/components/forms/DatePicker/index.js
> +  is24Hour: true,
Северная Америка, Япония

2021-06-17 08:42 UTC, olvipi commented on packages/ui/components/forms/DatePicker/index.js
> +  is24Hour: true,
24h тоже присутствует, но локальный стандарт 12h

2021-06-17 08:48 UTC, olvipi commented on packages/ui/components/forms/DatePicker/TimeSelect/index.js
> +      onChangeDate && onChangeDate(timeshtamp)
может в моде datetime ввести стейт выбора числа месяца isDateSelected

2021-06-17 08:49 UTC, olvipi commented on packages/ui/components/forms/DatePicker/TimeSelect/index.js
> +      onChangeDate && onChangeDate(timeshtamp)
плюс если есть minDate - maxDate можно вообще дисейблить время до выбора даты

2021-06-17 09:38 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/index.js
> +    const timeshtamp = moment(textInput, _formatInput)
а кстати да с timestamp что-то тупанул

2021-07-05 13:14 UTC, pturchik requested changes

2021-07-09 09:10 UTC, lilhakk commented on packages/babel-plugin-startupjs/moduleMap.json
> +    "DatePicker": "/components/forms/DatePicker",
А старый выпиливать?

2021-07-12 14:14 UTC, pturchik requested changes

2021-07-12 14:14 UTC, pturchik commented on packages/ui/components/forms/DatePicker/TimeSelect/index.js
> +        res.push({ label: index, value: index })
давай это все перепишем и будем работать со временем а не с числами которые ТИПО определяют время, а на вывод делать уже `.format(is24HourFormat ? ... : ..)`.

```js
const format = is24HourFormat ? ... : ...
time.format(format) // делаешь при выводе
```

2021-07-12 14:16 UTC, pturchik requested changes

2021-07-12 14:16 UTC, pturchik commented on packages/ui/components/forms/DatePicker/TimeSelect/index.js
> +      onChangeDate(timeshtamp)
timestamp not timeshtamp

2021-07-17 20:42 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/Calendar/slides/Days/index.js
> +  const matrixdMonthDays = useMemo(() => {
<img width="499" alt="Снимок экрана 2021-07-17 в 23 41 48" src="https://user-images.githubusercontent.com/20387883/126048914-f71caaf4-2cdc-461f-a249-e8d85e09d766.png">

2021-07-17 20:43 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/Calendar/slides/Days/index.js
> +  const matrixdMonthDays = useMemo(() => {
это массив массивов

2021-07-17 20:43 UTC, lilhakk commented on packages/ui/components/forms/DatePicker/Calendar/slides/Days/index.js
> +  const matrixdMonthDays = useMemo(() => {
d это опечатка

2021-07-19 13:37 UTC, pturchik requested changes

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +  useEffect(() => scrollToIndex(), [date])
нажимая к примеру по центру списка на 3-00 оно сразу у меня отскролит таймлайн так что 3-00 станет сверху?

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +    return !(new RegExp(/a/i).test(lt))
тут мы коммент добавить почему ищем `a`?

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +  }, [date])
а зачем нам всегда перечистывать при смене даты один и тот же массив? из-за disabled? тогда можно в `renderItem` и решать это, добавить extraProps или как он там `minDate + maxDate` чтоб оно тригерилось на их изменение что очень маловероятно будет и уже при выводе в disabled это и запихнуть. плюс надо key указать какой-то всем этим элементам чтобы они просто так не перерендеривались

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +            { length: 40, offset: 40 * index, index }
length:  (60 / minuteInterval ) * 24 ?

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.styl
> +.container
а зачем этот контейнер нужен?

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.styl
> +    flex-direction row
выше стоит row по умолчанию, а ниже column. что в итоге должно то быть?

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.styl
> +    flex-direction row
и зачем вообще здесь flex-direction? элементы flatlist'а разве так можно перестроить стилем родителя? аналогично c align-items, justiry-content? flatlist'а item'ы же должны заполнять все пространство им доступное и по сути сам flatlist контейнер'у надо кидать размеры какие-то или его item'емам

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.styl
> +    flex-direction row
у тебя ниже и кидается'ся `cell` ширина 12. здесь вообще не понятно зачем все эти `align, height, width, ...`

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/DateTimePicker.en.mdx
> +DateTimePicker DateTimePicker allows to display and change the date and time
`DateTimepicker` is repeated twice

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/DateTimePicker.en.mdx
> +## Простой пример
it is an english doc - `Simple example`

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/DateTimePicker.en.mdx
> +## Свойства
it is an english doc - `Props`

2021-07-19 13:37 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/DateTimePicker.en.mdx
> +onChangeDate - date and time selection handler, returns a timestamp
раз ты решил это не списком то мб как-то выделить названия свойства хотя бы жирным?

2021-07-20 09:21 UTC, lilhakk commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +  useEffect(() => scrollToIndex(), [date])
да

2021-07-20 09:24 UTC, lilhakk commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +  }, [date])
потому что там все отталкивается от выбранной даты

2021-07-20 09:37 UTC, lilhakk commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +            { length: 40, offset: 40 * index, index }
?

2021-07-20 09:37 UTC, lilhakk commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +            { length: 40, offset: 40 * index, index }
?

2021-07-21 12:54 UTC, pturchik requested changes

2021-07-21 12:54 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +  // to figure out whether to apply 12 hour fore
fore?

2021-07-21 12:54 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +  useEffect(() => scrollToIndex(), [date])
а зачем нам скролить куда-то если при выборе времени дейтпикер закрывается. при открытии таймлайн должен быть отскролен на середину выбраного || текущего времени

2021-07-21 12:54 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +    const index = preparedData.findIndex(item => _date === item.value)
а если положат дату как-то кастомно и криво то scrollToIndex на -1 не сломается?

2021-07-21 12:56 UTC, pturchik requested changes

2021-07-21 12:56 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +
при изменении месяца когда там будет то 5 строк дней то 6 строк дней timeselect тоже расширится и сожмется нормально?

2021-07-21 12:56 UTC, olvipi commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +  useEffect(() => scrollToIndex(), [date])
этот useEffect сработает при открытии так же

2021-07-21 12:58 UTC, pturchik requested changes

2021-07-21 12:58 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +  useEffect(() => scrollToIndex(), [date])
так он и должен срабатывать 1 раз при открытии и все

2021-07-21 12:58 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +
а что будет когда я меняю дату в календаре? ведь сейчас он реагирует на дату которую кинули в дейтпикере. если я буду крутить календарь и выбирать дату которая меньше больше min max?

2021-07-21 12:59 UTC, olvipi commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +  useEffect(() => scrollToIndex(), [date])
центровать можно сместя индекс на -2 например, если в зоне видимости 5 индексов и текущий индекс > 2

2021-07-21 13:09 UTC, olvipi commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +
при изменении даты меняется сетится день и месяц

2021-07-21 13:10 UTC, olvipi commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +
высота вкалендаря стабильная

2021-07-21 13:13 UTC, olvipi commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +
всегда 6 строк

2021-07-21 13:27 UTC, olvipi commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +    const index = preparedData.findIndex(item => _date === item.value)
тут надо подумать что бы найты ближейшее время на случай если открывается с текущим временем допустип 16:26 а интервал выставлен в 15 мин

2021-07-21 13:31 UTC, olvipi commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +  useEffect(() => scrollToIndex(), [date])
надо убрать  date из инпута

2021-07-21 16:03 UTC, pturchik requested changes

2021-07-21 16:03 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/TimeSelect/index.js
> +    View.case(ref=ref)
а зачем этот View нужен c рефкой если тебе достаточно useImpertiveHandle чтобы провернуть все махинации?

2021-07-22 08:20 UTC, pturchik requested changes

2021-07-26 08:24 UTC, pturchik requested changes

2021-07-26 08:24 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/index.js
> +    const toBottom = value - bottom
```
const bottom = value % 30
const top = interval - bottom
value = top > bottom ? bottom : top
```

зачем тебе столько много переменных это же можно решить в три строки

2021-07-26 19:16 UTC, merged