fix(ui/Modal): doc sandbox visible
startupjs/startupjs pull request #729
Opened 2021-07-21 13:16 UTC by lilhakk

2021-07-22 07:29 UTC, pturchik requested changes

2021-07-22 07:29 UTC, pturchik commented on packages/docs/client/components/Props/Constructor/index.js
> +      if (prop.defaultValue !== undefined) {
по идеи что хук выше что этот хук должны отработать 1 раз и никаких изменений Component быть не может. плюс чтобы не писать как в файле ниже эти if ($theProps.get()....) эту логику можно вынести в файл Props/index.js или в хук и там его заюзать и делать это с помощью throw promise который засетит дефолты и тогда никаких рейскондишенов не будет

2021-07-22 07:29 UTC, pturchik commented on packages/docs/client/components/Props/Constructor/index.js
> +      res.forEach(item => {
цикл какой-то задом наперед, у меня 1000 пропсов и 1 дефолт кинут, я пробегусь по 1000 чтобы найти 1 дефолт, это не правильно. тебе лучше будет бежать по props и если они есть то оверайдить.

2021-07-26 08:23 UTC, olvipi commented on packages/docs/client/components/Props/index.js
> +      possibleTypes: meta.type.value,
зачем два ключа с одинаковыми значениями?

2021-07-26 08:27 UTC, pturchik requested changes

2021-07-26 08:27 UTC, pturchik commented on packages/docs/client/components/Props/index.js
> +  }, [Component])
не будет у нас меняться компонент, поэтому делай throw promise который засетит эти дефолты и убирай if с `Renderer'a`

2021-07-26 18:51 UTC, merged