fix(mdx): docs style
startupjs/startupjs pull request #746
Opened 2021-08-05 10:58 UTC by lilhakk

2021-08-09 08:10 UTC, pturchik requested changes

2021-08-09 08:10 UTC, pturchik commented on packages/mdx/client/Code/index.js
> +    ).scroll
напиши класс в начале элемента пожалуйста, и не понятно чем тебя `root` не устраивал

2021-08-09 08:10 UTC, pturchik commented on packages/mdx/client/Code/index.js
> +      style=[textStyle, style]
ты уверен что `textStyle` должен упасть в `ScrollView`?

2021-08-09 08:10 UTC, pturchik commented on packages/mdx/client/Code/index.js
> +}
а для чего это нужно? что не так с тем как было до? это работает на мобилках?

2021-08-10 07:50 UTC, lilhakk commented on packages/mdx/client/Code/index.js
> +}
Это работает на мобилках
Эта функция разбивает код по строчно, до этого просто валялись Span`ы без какого-либо объединения
Соответсвенно, поскольку код в строчку написан, нет никаких переносов, если сужать экран, и появляется скролл

2021-08-12 09:45 UTC, merged