fix(ui/Tag): docs mobile
startupjs/startupjs pull request #747
Opened 2021-08-05 12:50 UTC by lilhakk

2021-08-09 08:19 UTC, pturchik requested changes

2021-08-09 08:19 UTC, pturchik commented on packages/ui/components/Tag/Tag.en.mdx
> +    <Tag style={{ marginTop: 8, marginRight: 8 }} color='error'>Error</Tag>
зачем все эти стили `Row` если `Code` блок просто должен быть скролируемый?

2021-08-09 08:22 UTC, pturchik requested changes

2021-08-09 08:22 UTC, pturchik commented on packages/ui/components/Tag/Tag.en.mdx
> +    <Tag style={{ marginTop: 8, marginRight: 8 }} color='error'>Error</Tag>
если и хочется представить все примеры в столбик то просто не нужно использовать `Row`

2021-08-09 19:59 UTC, lilhakk commented on packages/ui/components/Tag/Tag.en.mdx
> +    <Tag style={{ marginTop: 8, marginRight: 8 }} color='error'>Error</Tag>
щас они отображаются в строчку, при сужении переносятся в столбик, если не хватает места

2021-08-09 19:59 UTC, lilhakk commented on packages/ui/components/Tag/Tag.en.mdx
> +    <Tag style={{ marginTop: 8, marginRight: 8 }} color='error'>Error</Tag>
щас они отображаются в строчку, при сужении переносятся в столбик, если не хватает места

2021-08-09 19:59 UTC, lilhakk commented on packages/ui/components/Tag/Tag.en.mdx
> +    <Tag style={{ marginTop: 8, marginRight: 8 }} color='error'>Error</Tag>
щас они отображаются в строчку, при сужении переносятся в столбик, если не хватает места

2021-08-13 06:57 UTC, olvipi commented
не нужно после ввода скрола для екземлов

2021-08-13 08:14 UTC, closed without merging