fix(scrollable): header buttons mobile
startupjs/startupjs pull request #751
Opened 2021-08-05 16:55 UTC by lilhakk

2021-08-06 08:52 UTC, olvipi commented on packages/scrollable-anchors/client/example/index.styl
> +  +from($UI.media.tablet)
+tablet()

2021-08-06 08:52 UTC, olvipi commented on packages/scrollable-anchors/client/example/index.styl
> +  +from($UI.media.tablet)
+tablet()

2021-08-09 10:24 UTC, pturchik requested changes

2021-08-09 10:24 UTC, pturchik commented on packages/scrollable-anchors/client/example/index.styl
> +  flex-direction column
а смысл заворачивать в `Row` блок чтобы давать ему `flex-direction: column`. положи просто его в Div а для медия запроса напиши как раз `flex-direction: row`.

2021-08-09 10:24 UTC, pturchik commented on packages/scrollable-anchors/client/example/index.js
> +        onPress=()=> setExtraContentVisibility(!extraContentVisibility)
а в чем смысл extra content'а? типо что перещитываются позиции якорей?

2021-08-09 18:45 UTC, lilhakk commented on packages/scrollable-anchors/client/example/index.js
> +        onPress=()=> setExtraContentVisibility(!extraContentVisibility)
это просто блок с текстом как я понял, возможно и так, для тестов больше сделал был наверное

2021-08-10 08:13 UTC, merged