docs: correct description for t function
startupjs/startupjs pull request #800
Opened 2021-09-07 21:32 UTC by simonvolkov

2021-09-08 06:52 UTC, olvipi requested changes

2021-09-08 06:52 UTC, olvipi commented on packages/i18n/readme/readme.ru.mdx
> +Чтобы не приходилось писать конфиг с переводами вручную можно использовать функцию - `t`
там кажется не надо писать конфиг с переводами вообще, он создается бабель плагином

2021-09-08 06:52 UTC, olvipi commented on packages/i18n/readme/readme.ru.mdx
> +При компиляции проекта будут найдены все файлы которые используют данную функцию, и сгенерируется конфиг в формате:
конфиг создается только для дефолтного языка и используется приватно, надо это из доки удалить

2021-09-08 06:52 UTC, olvipi commented on packages/i18n/readme/readme.ru.mdx
> +Чтобы не приходилось писать конфиг с переводами вручную можно использовать функцию - `t`
просто написать что функия t определяет что для этой фразы можно поределить перевод на странице /i18n, который будет использован для отображения при смене языка через useLang(), в нее надо передать ключ фразы и значение для языка по умолчанию

2021-09-08 06:52 UTC, olvipi commented on packages/i18n/readme/readme.ru.mdx
> +При компиляции проекта будут найдены все файлы которые используют данную функцию, и сгенерируется конфиг в формате:
переводы пишутся в БД

2021-09-23 16:07 UTC, cray0000 requested changes

2021-09-23 16:07 UTC, cray0000 commented on packages/i18n/readme/readme.ru.mdx
> +При компиляции проекта будут найдены все файлы которые используют данную функцию, и сгенерируется конфиг в формате:
@simonvolkov надо из примера удалить что типа создасться конфиг в формате "ru" и "ua". Как написал Саша, в конфиге будут чисто названия дефолтного языка (обычно это будет английский), а все переводы на другие языки уже надо будет в БД указывать с отдельной страницы.

Вообще удали из этой доки ВЕЗДЕ упоминание конфига тупо. Так как на самом деле единственный правильный способ работы с переводами теперь это исключительно через функцию `t()`. И конфиг вообще будет создаваться скрыто внутри папки node_modules автоматом во время компиляции.

Так что людям нет смысла забивать тут в доках голову деталями реализации, которая там под капотом происходит. Опиши просто процесс подключения и базовой настройки либы, описание АПИ функции `t()` с примерами использования, ну и заметку про страницу `/i18n`, что именно там непосредственно надо переводы вписывать

2021-09-23 17:11 UTC, cray0000 approved these changes

2021-09-23 17:11 UTC, merged