docs(ui/Divider): fix show variants divider in sandbox
startupjs/startupjs pull request #836
Opened 2021-11-01 10:56 UTC by simonvolkov

2021-11-01 14:53 UTC, pturchik requested changes

2021-11-01 14:53 UTC, pturchik commented on packages/ui/components/Divider/Divider.en.mdx
> +        $divider.set('style', { minWidth: 48 })
это для inline mode ? мы уже много раз говоирли о inline mode, в нём и не должно ничего быть видно. нужно понимать что такое inline mode и не нужны будут эти хаки

2021-11-01 15:52 UTC, simonvolkov commented on packages/ui/components/Divider/Divider.en.mdx
> +        $divider.set('style', { minWidth: 48 })
убрать?)

2021-11-01 15:53 UTC, simonvolkov commented on packages/ui/components/Divider/Divider.en.mdx
> +        $divider.set('style', { minWidth: 48 })
но $divider переменной там все равно не было

2021-11-02 07:05 UTC, pturchik commented on packages/ui/components/Divider/Divider.en.mdx
> +        $divider.set('style', { minWidth: 48 })
почему? она на 98 строке объявлялась

2021-11-02 07:23 UTC, simonvolkov commented on packages/ui/components/Divider/Divider.en.mdx
> +        $divider.set('style', { minWidth: 48 })
а, это в ru.mdx не объявлена была, из-за чего падала страница

2021-11-08 11:59 UTC, merged