docs(ui/Radio): fix number value in sandbox
startupjs/startupjs pull request #850
Opened 2021-11-23 07:46 UTC by simonvolkov

2021-11-25 07:44 UTC, pturchik requested changes

2021-11-25 07:44 UTC, pturchik commented on packages/ui/components/forms/Radio/Radio.en.mdx
> +      { value: 2, label: '2' }
а как это фиксит когда value - number? я выберу 'red', что будет?

2021-11-25 07:49 UTC, simonvolkov commented on packages/ui/components/forms/Radio/Radio.en.mdx
> +      { value: 2, label: '2' }
Будет выбрано 'red'
Если написать 1, то как раз выбереться 1

2021-11-25 08:18 UTC, pturchik commented on packages/ui/components/forms/Radio/Radio.en.mdx
> +      { value: 2, label: '2' }
каким образом если checked это тот где stringifyValue(option) === stringifyValue(value)

2021-11-25 09:28 UTC, simonvolkov commented on packages/ui/components/forms/Radio/Radio.en.mdx
> +      { value: 2, label: '2' }
https://user-images.githubusercontent.com/20387883/143415384-a95d534b-2459-43c4-a1c2-2fbc99543349.mov

2021-11-26 07:37 UTC, pturchik commented on packages/ui/components/forms/Radio/Radio.en.mdx
> +      { value: 2, label: '2' }
это же плохо выглядит, у тебя опций половину для одного типа и половину для другого. просто завяжись на смену value type и пересечивай options

2021-11-26 07:49 UTC, simonvolkov commented on packages/ui/components/forms/Radio/Radio.en.mdx
> +      { value: 2, label: '2' }
https://github.com/startupjs/startupjs/blob/master/packages/docs/client/components/Props/Constructor/ValueCell/index.js#L160

Дело в том что тип пропа это не сам проп, а внутренняя переменная

2021-11-26 07:51 UTC, simonvolkov commented on packages/ui/components/forms/Radio/Radio.en.mdx
> +      { value: 2, label: '2' }
пока не понятно как проверит ее изменения чтобы ничего не поломать

2021-12-01 09:18 UTC, closed without merging