TextInput: fix focus and survey onLabelPress bugs
startupjs/startupjs pull request #855
Opened 2021-12-08 10:31 UTC by AsiyeKk

2021-12-08 12:52 UTC, pturchik requested changes

2021-12-08 12:52 UTC, pturchik commented on packages/ui/components/forms/Input/inputs.js
> +    getProps: ({ value, $value, readonly, onChangeText }) => ({
тебе выше надо где создаются комопненты через wrapInput убрать isLabelClickable для всех кому задается `true` и для всех у кого уберешь в inputs объекте в configuration как ты сделала для `text` задать его основываясь на readonly + disabled

2021-12-08 12:52 UTC, pturchik commented on packages/ui/components/forms/Input/wrapInput.js
> +              inputRef.current.focus && inputRef.current.focus()
эта проблема не здесь, эта проблема в том что в TextInput/input.js, там в _onLabelPress надо вызвать inputRef.focus(), но при этом надо ещё inputRef чтобы не использовал ref. а когда ты это уберешь надо проверить ещё что autosuggest норм работает, потому что в нём рефка инпута передается в abstractpopover который вызывает ref.current.measure

2021-12-09 08:26 UTC, fcbvirus0k commented on packages/ui/components/forms/Input/inputs.js
> +      configuration: { isLabelClickable: !disabled || !readonly },
почему `||`?

2021-12-09 08:26 UTC, fcbvirus0k commented on packages/ui/components/forms/Input/inputs.js
> +      configuration: { isLabelClickable: !disabled },
а у намбер инпута нет ридонли пропса?

2021-12-09 10:15 UTC, AsiyeKk commented on packages/ui/components/forms/Input/inputs.js
> +      configuration: { isLabelClickable: !disabled },
проверила, есть такой пропс

2021-12-20 08:26 UTC, pturchik requested changes

2021-12-20 08:26 UTC, pturchik commented on packages/ui/components/forms/Input/inputs.js
> -    isLabelColoredWhenFocusing: true,
зачем ты этот флаг удалила?

2021-12-21 08:35 UTC, merged