refactor (DateTimePicker): add the ability to show input icon
startupjs/startupjs pull request #919
Opened 2022-03-02 07:56 UTC by AsiyeKk

2022-03-09 09:19 UTC, narimandev requested changes

2022-03-09 09:19 UTC, narimandev commented on packages/ui/components/forms/DateTimePicker/index.js
> +    onSecondaryIconPress: () => _onChangeDate(undefined)
value = getDate(value)
setTextInput(getFormatDate(value))
это нужно убрать из `_ onChangeDate`, этот код дублируется в useEffect

2022-03-14 13:33 UTC, narimandev requested changes

2022-03-14 13:33 UTC, narimandev commented on packages/ui/components/forms/DateTimePicker/index.js
> +  const isUncontrolled = useMemo(() => typeof $visible === 'undefined', [])
`visible` тоже нужно

2022-03-14 13:33 UTC, narimandev commented on packages/ui/components/forms/DateTimePicker/index.js
> +  function _onCLose (args) {
_onClose

2022-03-14 13:33 UTC, narimandev commented on packages/ui/components/forms/DateTimePicker/index.js
> +    console.log('[@startupjs/ui] DateTimePicker: onFocus is deprecated, use onOpen instead')
постоянно будет вылетать консоль лог, надо и в инпуте поправить

2022-03-17 08:54 UTC, pturchik requested changes

2022-03-17 08:54 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/index.js
> +    onChangeVisible()
onChangeVisible(false)

2022-03-17 08:54 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/index.js
> +    onChangeVisible()
onChangeVisible(false)

2022-03-17 08:54 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/index.js
> +        Div.popoverOverlay(feedback=false onPress=()=> onChangeVisible())
onChangeVisible(false)

2022-03-17 08:54 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/index.js
> +    onSecondaryIconPress: () => onChangeDate && onChangeDate(undefined)
secondaryIcon, onSecondaryIconPress надо написать напрямую в TextInput, в renderInput они не должны лететь.

2022-03-17 08:54 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/index.js
> +      = renderInput(Object.assign({ onFocus, onBlur }, inputProps))
а как теперь если есть renderInput можно будет в нём изменить $visible ? наверное надо кидать ещё onChangeVisible теперь вместо $visible

2022-03-17 08:54 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/index.js
> +      = renderInput(Object.assign({ onFocus, onBlur }, inputProps))
и оставь комментарий возле renderInput
```
# NOTE
// Do we need to pass properties to 'renderInput' at all?
```

2022-03-17 09:26 UTC, AsiyeKk commented on packages/ui/components/forms/DateTimePicker/index.js
> +      = renderInput(Object.assign({ onFocus, onBlur }, inputProps))
все работает без передачи  onChangeVisible в renderInput. получается, что значение visible меняется в компоненте, который передается в renderInput

2022-03-17 11:39 UTC, narimandev commented on packages/ui/components/forms/DateTimePicker/index.js
>    }
`onDismiss` не нужен в `AbstractPopover`, там есть `renderWrapper` который будет подложкой для закрытия, а `Drawer` нужен `onDismiss`

2022-03-17 12:57 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/index.js
> +      = renderInput(Object.assign({ onFocus, onBlur }, inputProps))
```js
return pug`
  DateTimePicker(renderInput=...)
  DateTimePicker(renderInput=... $visible=$visible)
  DateTimePicker(renderInput=... visible=visible)
`

function renderInput () {
  return pug`
     Div
        Span Click me
  `
}
```

все три примера работают ? +)

2022-03-17 19:58 UTC, narimandev approved these changes

2022-03-18 14:10 UTC, pturchik requested changes

2022-03-18 14:10 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/index.js
> +  // Do we need to pass properties to 'renderInput' at all?
этот комментарий надо написать там где вызывается `= renderInput(...)`

2022-03-21 11:56 UTC, pturchik requested changes

2022-03-21 11:56 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/docs/DateTimePicker.en.mdx
> +There are three options for managing the state of a DateTimePicker:
... for managing visiblity of a DateTimePicker:
поменяй и в модалке сразу пожалуйста

2022-03-21 11:56 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/docs/DateTimePicker.en.mdx
> +3. Not passing the `visible` property.
3. Uncontrolled.
```js
const [date, onChangeDate] = useState()
return pug`
  DateTimePicker(
    date=date
    onChangeDate=onChangeDate
  )
`
```

2022-03-21 11:56 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/docs/DateTimePicker.en.mdx
> +2. By passing the `visible` property that determines whether DateTimePicker is visible.
By passing the `visible`, `onRequestOpen` and `onRequestClose` properties ...

2022-03-21 11:56 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/docs/DateTimePicker.ru.mdx
> +Для управления состоянием DateTimePicker есть три варианта:
Для управления видимостью `DateTimePicker` есть три способа
поменяй пожалуйста и в модалке

2022-03-21 11:56 UTC, pturchik commented on packages/ui/components/forms/DateTimePicker/docs/DateTimePicker.ru.mdx
> +2. Передав свойство `visible`, которое определяет является ли DateTimePicker видимым.
если ты пишешь DateTimePicker (прям имя собственное компонента) то желательно такое выделять в `

2022-03-22 10:17 UTC, merged