feat(auth-local): implements email confirmation
startupjs/startupjs pull request #942
Opened 2022-04-22 21:07 UTC by zheoreh

2022-04-26 20:09 UTC, pturchik requested changes

2022-04-26 20:09 UTC, pturchik commented on packages/auth-local/isomorphic/constants.js
> +export const DEFAULT_CONFIRM_EMAIL_TIME_LIMIT = 60 * 1000 * 60 * 24 * 3 // 3 days in ms
наверное надо в форме логина добавить чтобы если чувак пытается залогиниться и ему прилетела ошибка что email unconfirmed то показывать ошибку что email unconfirmed **resend confirmation**

2022-04-26 20:18 UTC, pturchik requested changes

2022-04-26 20:18 UTC, pturchik commented on packages/auth-local/client/components/RegisterForm/index.js
> -import React, { useEffect, useRef } from 'react'
надо добавить какую-то базовую страницу для confirm email registration. а после confirm'а уже на клиенте по принципу других компонент будет идти на redirectUrl в этой компоненте которая по дефолту '/'

2022-04-29 08:35 UTC, zheoreh commented
<img width="520" alt="Screenshot 2022-04-28 at 21 09 51" src="https://user-images.githubusercontent.com/8188225/165911162-3d25076d-1fe3-43ee-bf91-53ad3485fc53.png">
<img width="486" alt="Screenshot 2022-04-28 at 21 10 02" src="https://user-images.githubusercontent.com/8188225/165911175-03e5aa1a-7e3d-4688-a6c4-680c586849c8.png">
<img width="525" alt="Screenshot 2022-04-28 at 21 13 57" src="https://user-images.githubusercontent.com/8188225/165911176-ac9d3fb0-ec29-4210-9614-7e48d58ba3c2.png">

2022-04-29 08:48 UTC, zheoreh commented
@pturchik еще немного странно, что не auth-local реализует страницы логина, реги и т.д.

2022-05-16 19:44 UTC, pturchik requested changes

2022-05-16 19:44 UTC, pturchik commented on packages/auth-local/server/helpers/onBeforeResendConfirmation.js
> +  const $$auths = model.query('auths', { email })
смотрю что в библиотеке есть проблема и в других местах связанная с поиском пользователя как здесь.
если глянуть в BaseProvider то видно что есть options.patchFindUserQuery, оно должно влиять на любой поиск пользователя иначе можно найти не правильного. хорошо было бы если бы тут сразу же зарефакторил это. к примеру можно создавать провайдера и дальше от него вызывать методы, можно создать например

findUserQuery куда перенести `if (this.options.patchFindUserQuery) ...`, можно ещё допом покрыть создав findUser и использовать его там где нужно узнать есть пользователь или нет, а можно допустим возвращать user + unsubscribe метод и использовать вообще везде.
потом этот findUser переиспользовать в findOrCreateUser.
и зарефакторить все места где идет query = { email } в коллекцию auths в auth-local библиотеке

2022-05-16 19:44 UTC, pturchik commented on packages/auth-local/server/helpers/onBeforeResendConfirmation.js
> +    return next('Service is not available for this user')
User does not exist ?

2022-05-16 19:44 UTC, pturchik commented on packages/auth-local/server/helpers/confirmEmail.js
> +  if (unconfirmed.expiresAt < Date.now()) {
а зачем объект иметь здесь? имеет смысл разве что в объекте auth.local.unconfirmed = date

2022-05-16 19:44 UTC, pturchik commented on packages/auth-local/server/Provider.js
> +    const { hash, salt, unconfirmed, confirmEmail } = this.profile
что за confirmEmail и зачем он нам дальше?

2022-05-17 08:45 UTC, pturchik commented on packages/auth-local/server/helpers/onBeforeResendConfirmation.js
> +  const $$auths = model.query('auths', { email })
ещё обрати внимание в тех местах где будет рефакторить `query('auths', ...` есть места где делается `query('auths', { email })`, их нужно зарефакторить на твой findUser в котором надо сделать правильное квери в providers.local.email

2022-05-17 10:20 UTC, zheoreh commented on packages/auth/isomorphic/getAuthRoutes.js
> -  }
router.get(CONFIRM_REGISTRATION_URL - это веброут. с самого приложения запрос на него не идет.

2022-05-17 12:26 UTC, zheoreh commented on packages/auth-local/server/helpers/onBeforeResendConfirmation.js
> +  const $$auths = model.query('auths', { email })
честно говоря не хочется трогать этот какашечный провайдер, который по большему счету используется для создания юзера, нежели для работы с ним. в локальном провайдере есть loadAuthData могу заюзать его для получения данных юзера по емейлу, он как рас таки используется в нескольких местах. А так идея конечно понятна, но если ее реализовать, тогда отпадет loadAuthData а он в себе юзает loadAuthData из опций, если тот предоставлен, а я хз какие проекты его уже юзают. в общем геморойчик, который не хочется реализовывать в рамках конфирмации. Поэтому я пожалуй остановлюсь на loadAuthData

2022-05-17 13:11 UTC, zheoreh commented on packages/auth-local/server/helpers/onBeforeResendConfirmation.js
> +    return next('Service is not available for this user')
User is already confirmed

2022-05-17 14:37 UTC, pturchik approved these changes

2022-05-17 14:39 UTC, merged