feat(ui/RangeInput): implements single/multiple range input
startupjs/startupjs pull request #952
Opened 2022-05-23 21:06 UTC by zheoreh

<img width="812" alt="Screenshot 2022-05-24 at 00 04 34" src="https://user-images.githubusercontent.com/8188225/169906025-b3286034-4e2a-4a0d-ae81-6eee0e1efe0f.png">

2022-05-23 21:21 UTC, cray0000 commented
@zheoreh надо не в styleguide'овский force compile добавлять, а глобально в дефолтные force compile в bundler'е. А то когда люди будут проект создавать новый у них же оно компилиться не будет

2022-05-23 22:14 UTC, zheoreh commented
@cray0000 ничего не понял. если я уберу из форскомпайла стайлгайда, то он не соберется и не запустится. а в других проектах я так понимаю все придется добавлять этот модуль в форскомпайл

2022-05-23 22:28 UTC, cray0000 commented
@zheoreh поскольку @startupjs/ui в дефолтном startupjs проекте юзается, и твой RangeInput это часть ui, значит надо добиться того, чтобы по дефолту оно форскомпайлило этот модуль. Свяжись с @pturchik и придумайте как этого лучше всего добиться. Один из вариантов это в файле `ui/startupjs.config.cjs` указать массив пакетов для web, ток в этом случае надо и сам `@startupjs/ui` тоже указать в массиве.

Другой вариант это в bundler'е сделать чтобы пакеты, начинающиеся с неймспейса и потом с 'react-native-' по-умолчанию форс компилились. И наверн лучше именно это и сделать. Так как там и так уже есть такое для пакетов, начинающихся с 'react-native-', а у твоего пакета просто в названии еще есть неймспейс, поэтому он его не подхватывает, что скорее является багом.

2022-05-26 13:57 UTC, zheoreh commented
<img width="840" alt="Screenshot 2022-05-26 at 16 49 5" src="https://user-images.githubusercontent.com/8188225/170502290-41bcf741-c528-4217-980d-3b19dc634ee3.png">
@pturchik чет не не очень такой диз)

2022-05-26 14:10 UTC, cray0000 commented
@zheoreh оригинальные размеры кнопочек были правильные. По гайдлайнам материал дизайна нажимаемая область должна быть минимум 24px. Ну и соьственно весь UX у нас исключительно mobile first, мышку мы полностью игнорим вообще, UX десктопный для нас второстепенен.

2022-05-30 07:31 UTC, zheoreh commented
<img width="811" alt="Screenshot 2022-05-30 at 10 31 40" src="https://user-images.githubusercontent.com/8188225/170940580-ddd1de7e-2292-4a3b-a78c-c7df432d1e88.png">

2022-05-30 10:03 UTC, pturchik requested changes

2022-05-30 10:03 UTC, pturchik commented on packages/ui/components/forms/RangeInput/Label/index.js
> +      if Number.isFinite(oneMarkerLeftPosition) && Number.isFinite(oneMarkerValue)
а сюда могут залетать какие-то странные значения?

2022-05-30 10:03 UTC, pturchik commented on packages/ui/components/forms/RangeInput/Label/index.js
> +const width = 14
это width чего?

2022-05-30 10:06 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/index.js
> +export default observer(RangeInput, { forwardRef: true })
когда юзается это компонент под капотом у Input в него передается рефка и без этой опции была то ли ошибка, толи варнинг от которого я избавился таким приемом

2022-05-30 10:10 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/Label/index.js
> +      if Number.isFinite(oneMarkerLeftPosition) && Number.isFinite(oneMarkerValue)
не выяснял, просто повторил как в вендорном компоненте.

2022-05-30 10:15 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/Label/index.js
> +const width = 14
я профукал один момент. это должна быть дефолтная ширина у стиля лейбла. и получился в итоге харкод. правда у вендорного компонента тоже в одном моменте получился хардкод

2022-05-30 11:43 UTC, pturchik requested changes

2022-05-30 11:43 UTC, pturchik commented on packages/ui/components/forms/RangeInput/index.js
> +  const _twoMarkers = Array.isArray(value) && value.length > 1
может лучше мы заведем какой-то пропс range: bool, и value дефолтное будет min или [min, max]?

2022-05-30 11:43 UTC, pturchik commented on packages/ui/components/forms/RangeInput/Label/index.styl
> +  font-size 11px
font(caption)

2022-05-30 11:43 UTC, pturchik commented on packages/ui/components/forms/RangeInput/Label/index.js
> +      if Number.isFinite(oneMarkerLeftPosition) && Number.isFinite(oneMarkerValue)
тогда надо написать какой-то комментарий что это скопировано из дефолтного лейбла в библиотеке

а чем дефолтный не подошёл лейбл?

2022-05-30 11:43 UTC, pturchik commented on packages/ui/components/forms/RangeInput/RangeInput.en.mdx
> +Slider component with one or two markers.
может быть - Sliders allow users to make selections from a range of values?

2022-05-30 11:43 UTC, pturchik commented on packages/ui/components/forms/RangeInput/RangeInput.en.mdx
> +Specify `showLabel` property
ну и доки под новое апи нужно будет поменять

2022-05-30 16:20 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/index.js
> +  const _twoMarkers = Array.isArray(value) && value.length > 1
была бы такая необходимость)

2022-05-30 16:24 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/Label/index.js
> +      if Number.isFinite(oneMarkerLeftPosition) && Number.isFinite(oneMarkerValue)
я так понимаю, что таким образом проверяется число ли здесь находится.

2022-05-30 17:11 UTC, zheoreh commented
<img width="815" alt="Screenshot 2022-05-30 at 20 10 55" src="https://user-images.githubusercontent.com/8188225/171036613-807b8cb7-d078-47cd-8f79-58bacc7c3bc5.png">

2022-05-31 23:29 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/Label/index.js
> +      if Number.isFinite(oneMarkerLeftPosition) && Number.isFinite(oneMarkerValue)
в дефолтном не прокидываются стили в отличии от маркера

2022-06-01 11:42 UTC, pturchik requested changes

2022-06-01 12:13 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/Label/index.js
> +          Span.labelText(styleName={ pressed: oneMarkerPressed })= oneMarkerValue
не видел ни одного класса с дефисом) короче просто переименовал

2022-06-01 12:33 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/index.js
> +  }, [range, value, min, max, JSON.stringify(options)])
нет. оптионс именно чтобы задать конкретные возможные значения для выбора в диапозоне. зачем мне эти лейблы на шкале, когда я над ползунком вижу его значение и без труда могу установить нужное мне значение? кроме того вендорный модуль эти значения не отображает, поэтому все не так как в лингве) и еще этот модуль опускает min и max когда options задан, поэтому я принимаю его в расчет при выяснении минимального и максимального значения для дефолтных значений ползунков. зачем фровать промис? малопонятная конструкция по сравнению с юзффектом и нужен ли мне сброс рендера компонента? думаю, что нет)

2022-06-01 12:34 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/Label/index.styl
> +  bottom -10px
он сверху, как на скрине. просто у вендорного слайдера такой лейаут, что лейбл слишком высоко и из-за асболюта вылазит выше контейнера слайдера из-за чего может нахлестываться на сиблинг элементы

2022-06-02 08:43 UTC, pturchik requested changes

2022-06-02 08:55 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/index.js
> +  }, [range, value, min, max, JSON.stringify(options)])
1. ок. зафроваем.
2. если память не изменяет. на счет опшинс/маркс я не вижу проблемы в том, что max и min и step отпадают. ты их вообще указывать не будешь и по пропам не будет каши. мне проще раз список доступных значений указать, чем указывать аж три пропа и такое поведение я уже встречал ранее. почему слишком, всего два варианта) не можем.

2022-06-02 10:42 UTC, zheoreh commented
@cray0000  Кстати за размер слайдера(ползунка) можно не переживать, у нас еще есть тач контейнер который по дефолту 50 на 50. поэтому можно сосредоточиться на дизайне

2022-06-03 09:49 UTC, zheoreh commented
https://www.loom.com/share/618a29d37f974529ac4132c850248a54

2022-06-07 09:27 UTC, pturchik requested changes

2022-06-07 09:27 UTC, pturchik commented on packages/ui/components/forms/RangeInput/index.js
> +      values=_value
values

2022-06-07 09:52 UTC, zheoreh commented on packages/ui/components/forms/RangeInput/Label/index.js
> +    Div.label(style={ left: position - styles.label.width / 2 })
была мысль, но она не реализуема, так как лейбл маркера появляется на онпресе по маркеру. лейбл может быть дивом с тултипом, но чтобы появился тултип, нужно навести на див, что не выполнимо, т.к. лейбл появляется только на пресе по маркеру

2022-06-07 13:27 UTC, pturchik approved these changes

2022-06-07 13:28 UTC, merged