feat(auth-local/RegisterForm): add 'complexPassword' option
startupjs/startupjs pull request #992
Opened 2022-11-30 14:32 UTC by nbhim12

2022-11-30 15:30 UTC, cray0000 requested changes

2022-11-30 15:30 UTC, cray0000 commented on packages/auth-local/client/components/RegisterForm/utils/joi.js
> +const defaulPasswordValidationSettings = Joi.string().required()
`default`

please use a spell checker in your IDE. For example for VS Code:
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2022-11-30 15:36 UTC, cray0000 requested changes

2022-11-30 15:36 UTC, cray0000 commented on packages/auth-local/client/components/RegisterForm/utils/joi.js
> +    .regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%_*?&#$^])[A-Za-z\d_@$!%*-?&#^]{8,}$/)
please add a comment above this line describing what this regex checks for

2022-11-30 15:40 UTC, cray0000 commented on packages/auth-local/client/components/RegisterForm/utils/joi.js
> +    .regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%_*?&#$^])[A-Za-z\d_@$!%*-?&#^]{8,}$/)
actuallyy nevermind, it is described in the `string. pattern. base` below. I was just confused with the special characters you have in the regex

2022-11-30 16:43 UTC, cray0000 requested changes

2022-11-30 16:59 UTC, cray0000 approved these changes

2022-11-30 18:46 UTC, zheorekh commented on packages/auth-local/client/components/RegisterForm/index.js
> +  complexPassword
props must be before callbacks + alphabet order

2022-12-01 07:36 UTC, zheorekh commented on packages/auth-local/client/components/RegisterForm/index.js
> +  passwordCheckType: PropTypes.string,
it doesn't expect any string.

2022-12-01 08:25 UTC, zheorekh approved these changes
LGTM

2022-12-22 17:32 UTC, cray0000 approved these changes

2022-12-22 17:32 UTC, merged