Row component: fix  mobile bug
startupjs/startupjs pull request #995
Opened 2022-12-19 06:16 UTC by AsiyeKk

<img width="1151" alt="Снимок экрана 2022-12-16 в 11 04 15" src="https://user-images.githubusercontent.com/95744828/208360257-0e907765-125b-4605-bfe0-b7fb512c2b17.png">

2022-12-19 10:04 UTC, zheorekh requested changes

2022-12-19 14:08 UTC, zheorekh approved these changes

2022-12-19 17:59 UTC, zheorekh commented
@Yska твой выход)

2022-12-22 09:58 UTC, zheorekh commented
@cray0000 может ты глянешь да смержишь?

2022-12-22 17:24 UTC, cray0000 approved these changes

2022-12-22 17:24 UTC, merged

2022-12-22 21:08 UTC, pvturchik commented
https://reactnative.dev/docs/stylesheet#flatten

flatten принимает массив. не нужно никакие дефолт в виде {}, а оставить как было и передать [style].

2022-12-22 21:08 UTC, pvturchik commented
`style = StyleSheet.flatten(style)` -> style = StyleSheet.flatten([style])