Fix ios and android bugs
startupjs/startupjs pull request #997
Opened 2022-12-21 13:44 UTC by AsiyeKk

<img width="1440" alt="Снимок экрана 2022-12-21 в 11 19 38" src="https://user-images.githubusercontent.com/95744828/208918448-5cca30db-2fab-4903-a834-b19950daec75.png">
<img width="1440" alt="Снимок экрана 2022-12-21 в 13 29 29" src="https://user-images.githubusercontent.com/95744828/208918476-4121c81a-a507-498f-96d9-29e1c18ede2d.png">

<img width="1414" alt="Снимок экрана 2022-12-20 в 15 05 26" src="https://user-images.githubusercontent.com/95744828/208918608-7c6a48bc-e83b-4df6-ade6-ed2b49f9f9df.png">
<img width="1306" alt="Снимок экрана 2022-12-21 в 13 22 23" src="https://user-images.githubusercontent.com/95744828/208918625-92d9f63c-c32a-4364-9427-8cef6c55ae8e.png">

<img width="1414" alt="Снимок экрана 2022-12-20 в 17 27 55" src="https://user-images.githubusercontent.com/95744828/208918793-4b6b03e6-18c5-4796-be06-8dd40fd428e7.png">
<img width="1358" alt="Снимок экрана 2022-12-21 в 16 06 29" src="https://user-images.githubusercontent.com/95744828/208918757-20b9ce12-0977-4a9c-900e-cd3accaeaf77.png">

<img width="1306" alt="Снимок экрана 2022-12-21 в 13 19 33" src="https://user-images.githubusercontent.com/95744828/208918512-92fc866f-26c7-41a4-b9b1-526128daad36.png">

<img width="1414" alt="Снимок экрана 2022-12-20 в 15 58 55" src="https://user-images.githubusercontent.com/95744828/208919038-b6ea154e-2265-4b08-bca4-6dabb746fb8b.png">

2022-12-21 14:52 UTC, zheorekh requested changes
Возможно следует вынести кнопнку "Назад" в компонент вместе с хуком, чтобы реюзать это дело и не плодить стили

2022-12-21 14:52 UTC, zheorekh commented on packages/auth/isomorphic/getAuthRoutes.js
> +    filters: [filters.isNotLoggedIn('/profile?customParam=dummy')]
Это затронет все проекты которые используют модуль авторизации

2022-12-21 14:52 UTC, zheorekh commented on packages/scrollable-anchors/client/example/index.js
> +import { useHistory } from 'react-router-native'
import { useHistory } from '@startupjs/app'

2022-12-22 15:18 UTC, zheorekh commented
LGTM

2022-12-22 15:18 UTC, zheorekh approved these changes

2022-12-22 17:29 UTC, cray0000 approved these changes

2022-12-22 17:29 UTC, merged